// <auto-generated />
using Harborline.Api.LocalNodeHost.Data.Calendar;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Calendar.Migrations;

[DbContext(typeof(NodeLocalCalendarDbContext))]
partial class NodeLocalCalendarDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260920033344_CalendarCapacityEpochs";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Calendar.NodeCalendarCapacityEpochRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("Resource")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("resource");

                b.Property<long>("Epoch")
                    .HasColumnType("INTEGER")
                    .HasColumnName("epoch");

                b.HasKey("TenantId", "Resource");

                b.ToTable("calendar_capacity_epochs", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Calendar.NodeCalendarEventRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("Id")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<string>("SnapshotJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("snapshot_json");

                b.HasKey("TenantId", "Id");

                b.HasIndex("TenantId");

                b.ToTable("calendar_events", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Calendar.NodeCalendarRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("Id")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<string>("SnapshotJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("snapshot_json");

                b.HasKey("TenantId", "Id");

                b.HasIndex("TenantId");

                b.ToTable("calendars", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Calendar.NodeResourceAvailabilityRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<int>("ResourceKind")
                    .HasColumnType("INTEGER")
                    .HasColumnName("resource_kind");

                b.Property<string>("ResourceValue")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("resource_value");

                b.Property<string>("SnapshotJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("snapshot_json");

                b.HasKey("TenantId", "ResourceKind", "ResourceValue");

                b.HasIndex("TenantId");

                b.ToTable("resource_availability", (string)null);
            });
#pragma warning restore 612, 618
    }
}
