// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Comms;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Comms.Migrations
{
    [DbContext(typeof(NodeLocalCommsDbContext))]
    [Migration("20260620133344_CommsInitial")]
    partial class _20260620133344_CommsInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.4.26230.115");

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Comms.NodeMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AuthorIssuerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("author_issuer_id");

                    b.Property<string>("AuthorPartyId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("author_party_id");

                    b.Property<long>("AuthoredAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("authored_at");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("NonceGuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("nonce");

                    b.Property<string>("SignatureB64Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("signature");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "AuthoredAtUtc");

                    b.ToTable("messages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
