// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Drafts;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Migrations.Drafts;

[DbContext(typeof(NodeLocalDraftsDbContext))]
partial class NodeLocalDraftsDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260701175903_AddSubmissionDraftTable";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Drafts.SubmissionDraftRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("CaseId")
                    .HasColumnType("TEXT")
                    .HasColumnName("case_id");

                b.Property<string>("PartyId")
                    .HasColumnType("TEXT")
                    .HasColumnName("party_id");

                b.Property<byte[]>("Body")
                    .IsRequired()
                    .HasColumnType("BLOB")
                    .HasColumnName("body");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_at_utc");

                b.Property<string>("DefinitionId")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("definition_id");

                b.Property<string>("DefinitionVersion")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("definition_version");

                b.Property<string>("EngineVersion")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("engine_version");

                b.Property<DateTimeOffset?>("ExpiresAtUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("expires_at_utc");

                b.Property<string>("FormId")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("form_id");

                b.Property<string>("LocaleChainJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("locale_chain_json");

                b.Property<string>("SchemaRef")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("schema_ref");

                b.Property<string>("SubjectId")
                    .HasColumnType("TEXT")
                    .HasColumnName("subject_id");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("updated_at_utc");

                b.HasKey("TenantId", "CaseId", "PartyId");

                b.HasIndex("ExpiresAtUtc")
                    .HasDatabaseName("ix_form_drafts_expires_at");

                b.HasIndex("TenantId", "PartyId")
                    .HasDatabaseName("ix_form_drafts_tenant_party");

                b.HasIndex("TenantId", "SubjectId")
                    .HasDatabaseName("ix_form_drafts_tenant_subject");

                b.ToTable("form_drafts", (string)null);
            });
#pragma warning restore 612, 618
    }
}
