// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Leases;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Leases.Migrations
{
    [DbContext(typeof(NodeLocalLeaseDbContext))]
    partial class NodeLocalLeaseDbContextModelSnapshot : ModelSnapshot
    {
        // If you encounter a merge conflict in the line below, it means you need to
        // discard one of the migration branches and recreate its migrations on top of
        // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
        public override string LastMigrationId => "20260614220950_LeaseInitial";

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Leases.LeaseRecord", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auto_renew");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("company");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("TEXT")
                        .HasColumnName("monthly_rent");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("property");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("TermCadence")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("term_cadence");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.HasKey("Name");

                    b.HasIndex("Property");

                    b.HasIndex("Status");

                    b.ToTable("leases", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
