// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Comms;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Comms.Migrations
{
    [DbContext(typeof(NodeLocalCommsDbContext))]
    partial class NodeLocalCommsDbContextModelSnapshot : ModelSnapshot
    {
        // If you encounter a merge conflict in the line below, it means you need to
        // discard one of the migration branches and recreate its migrations on top of
        // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
        public override string LastMigrationId => "20260621000000_CommsConversationId";

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Comms.NodeMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AuthorIssuerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("author_issuer_id");

                    b.Property<string>("AuthorPartyId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("author_party_id");

                    b.Property<long>("AuthoredAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("authored_at");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id")
                        .HasDefaultValue("team");

                    b.Property<string>("NonceGuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("nonce");

                    b.Property<string>("SignatureB64Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("signature");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "AuthoredAtUtc");

                    b.HasIndex("TenantId", "ConversationId", "AuthoredAtUtc");

                    b.ToTable("messages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
