// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Admission;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Admission.Migrations
{
    [DbContext(typeof(NodeLocalAdmissionDbContext))]
    [Migration("20260621114414_AdmissionTokensInitial")]
    partial class _20260621114414_AdmissionTokensInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.4.26230.115");

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Admission.NodeAdmissionTokenRecord", b =>
                {
                    b.Property<string>("TokenId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_id");

                    b.Property<string>("AnchorGenesisPartyId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("anchor_genesis_party");

                    b.Property<string>("AnchorGenesisPublicKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("anchor_genesis_key");

                    b.Property<string>("AnchorTeamId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("anchor_team_id");

                    b.Property<long>("IssuedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("issued_at");

                    b.Property<bool>("Redeemed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("redeemed");

                    b.Property<long>("TtlMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ttl_ms");

                    b.HasKey("TokenId");

                    b.ToTable("admission_tokens", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
