// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Admission;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Admission.Migrations;

[DbContext(typeof(NodeLocalAdmissionDbContext))]
[Migration("20260724123053_AdmissionAddPairingInviteBindings")]
partial class _20260724123053_AdmissionAddPairingInviteBindings
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Admission.NodeAdmissionTokenRecord", b =>
            {
                b.Property<string>("TokenId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("token_id");

                b.Property<string>("AnchorGenesisPartyId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("anchor_genesis_party");

                b.Property<string>("AnchorGenesisPublicKey")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("anchor_genesis_key");

                b.Property<string>("AnchorTeamId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("anchor_team_id");

                b.Property<long>("IssuedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("issued_at");

                b.Property<bool>("Redeemed")
                    .HasColumnType("INTEGER")
                    .HasColumnName("redeemed");

                b.Property<long>("TtlMilliseconds")
                    .HasColumnType("INTEGER")
                    .HasColumnName("ttl_ms");

                b.HasKey("TokenId");

                b.ToTable("admission_tokens", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Admission.NodePairingInviteBindingRecord", b =>
            {
                b.Property<string>("TokenId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("token_id");

                b.Property<string>("BoundPartyId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("bound_party_id");

                b.Property<string>("MembershipJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("membership_json");

                b.Property<string>("SessionCorrelationId")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("")
                    .HasColumnName("session_correlation_id");

                b.HasKey("TokenId");

                b.ToTable("pairing_invite_bindings", (string)null);
            });
#pragma warning restore 612, 618
    }
}
