import {test} from 'node:test'
import assert from 'node:assert/strict'
import {inputs,effective,validateReport,PROJECT,FILTER,tool} from '../candidate-mutation.mjs'
const required=['Health/A.cs','Health/B.cs']
const report=()=>({schemaVersion:'2',files:Object.fromEntries(required.map(f=>[f,{source:'literal\n',mutants:[{id:'1',status:'Killed',killedBy:['t1']}]}])),testFiles:{'tests.cs':{tests:[{id:'t1',name:'Actual route test'}]}}})
const source=()=> 'literal\n', exit={status:0,signal:null}
test('exact inputs reject traversal and unlisted presets',()=>{assert.doesNotThrow(()=>inputs('a'.repeat(40),PROJECT,'forms-authoring-files'));for(const args of [['main',PROJECT,'forms-authoring-files'],['a'.repeat(40),'../tests.csproj','forms-authoring-files'],['a'.repeat(40),PROJECT,'whole']])assert.throws(()=>inputs(...args))})
test('fixed Forms config and tenancy first-match exclusions',()=>{const def={slices:[{name:'earlier',include:['**/Authoriz*.cs']},{name:'scope-tenancy-identity-tenant',include:['Data/*Tenant*.cs']}]};const base={project:'Harborline.LocalNodeHost.csproj'};const forms=effective('forms-authoring-files',base,def);assert.equal(forms['test-case-filter'],FILTER);assert.deepEqual(forms.mutate,['**/Health/FormDefinitionRoutes.cs','**/Health/FormsAuthoringC3Wire.cs']);assert.equal(forms.thresholds.break,0);const tenancy=effective('tenancy-identity-tenant-full',base,def);assert.deepEqual(tenancy.mutate,['Data/*Tenant*.cs','!**/Authoriz*.cs']);assert.equal(tenancy['test-case-filter'],undefined)})
test('valid JSON cannot rescue nonzero/signal/spawn error',()=>{for(const bad of [{status:1},{status:null,signal:'SIGTERM'},{status:0,error:'spawn'}])assert.throws(()=>validateReport(report(),required,source,bad))})
test('requires both units, actual tested mutants and exact source',()=>{const missing=report();delete missing.files[required[1]];assert.throws(()=>validateReport(missing,required,source,exit));const zero=report();zero.files[required[1]].mutants[0].status='Ignored';assert.throws(()=>validateReport(zero,required,source,exit));assert.throws(()=>validateReport(report(),required,()=> 'other',exit))})
test('invalid or absent killed-test IDs fail; Timeout is separate, no named claim',()=>{for(const ids of [[],['missing']]){const r=report();r.files[required[0]].mutants[0].killedBy=ids;assert.throws(()=>validateReport(r,required,source,exit))}const r=report();r.files[required[0]].mutants[0].status='Timeout';const result=validateReport(r,required,source,exit);assert.equal(result.joins.length,1);assert.equal(result.summary.counts.Timeout,1);assert.equal(result.qualificationClaimed,false);assert.equal(result.namedControls,'pending-independent-review')})

test('real harmless fake tool emits JSON and raw exit1 remains rejected',()=>{const result=tool(process.execPath,['-e','console.log('+JSON.stringify(JSON.stringify({'files':{}}))+');process.exitCode=1'],{encoding:'utf8'});assert.deepEqual(JSON.parse(result.stdout),{files:{}});assert.equal(result.status,1);assert.throws(()=>validateReport(report(),required,source,result))})

// Independent literal policy and corruption controls; no SDK, build, mutation or lease.
import {baselineBinding,buildEnvironment,snapshot,assertSnapshot,deterministicZip} from '../candidate-mutation.mjs'
import {mkdtempSync,writeFileSync,readFileSync,utimesSync,rmSync,symlinkSync} from 'node:fs'
import os from 'node:os'
import path from 'node:path'
const row={score:60.23,break:60,tested:1139,killed:778,timeout:2,survived:359,noCoverage:156,measured:'2026-10-05',commit:'560dfc26',tool:'dotnet-stryker 5.0.0',run:'node eng/mutation-report.mjs --full --only apps/local-node-host/tests/tests.csproj --slice scope-tenancy-identity-tenant (winbox, 109 min); T-1005'}
test('only literal reviewed tenancy row changes; other policy or lower floor rejects',()=>{const a={note:'unchanged',slices:{'scope-tenancy-identity-tenant':{status:'pending'},other:{break:80}}};const b=structuredClone(a);b.slices['scope-tenancy-identity-tenant']=row;assert.equal(baselineBinding(JSON.stringify(a),JSON.stringify(b),'tenancy-identity-tenant-full'),'exact-reviewed372-row-only-fixed-floor60');assert.throws(()=>baselineBinding(JSON.stringify(a),JSON.stringify(b),'forms-authoring-files'));for(const mutate of [x=>x.slices.other.break=0,x=>x.slices['scope-tenancy-identity-tenant'].break=59,x=>x.note='changed']){const bad=structuredClone(b);mutate(bad);assert.throws(()=>baselineBinding(JSON.stringify(a),JSON.stringify(bad),'tenancy-identity-tenant-full'))}})
test('NoCoverage-only intended unit rejects and Timeout remains a tested non-kill',()=>{const r=report();r.files[required[1]].mutants=[{status:'NoCoverage'}];assert.throws(()=>validateReport(r,required,source,exit));r.files[required[1]].mutants=[{status:'Timeout'}];assert.equal(validateReport(r,required,source,exit).joins.length,1)})
test('tenancy inherited test filter cannot survive effective config',()=>assert.throws(()=>effective('tenancy-identity-tenant-full',{project:'Harborline.LocalNodeHost.csproj','test-case-filter':'narrow'},{slices:[{name:'scope-tenancy-identity-tenant',include:['**']}] })))
test('scrub removes broker/credential/GH/cache/startup authority and records only approved env',()=>{const env=buildEnvironment({PATH:'/usr/bin',DOTNET_ROOT:'/usr/share/dotnet',ACTIONS_RUNTIME_TOKEN:'secret',GITHUB_TOKEN:'secret',GH_TOKEN:'secret',GITHUB_ENV:'/authority',ACTIONS_CACHE_URL:'authority',NODE_OPTIONS:'--require attacker',DOTNET_STARTUP_HOOKS:'attacker',NUGET_PACKAGES:'/shared',HOME:'/credential-home',GIT_CONFIG_COUNT:'1'},'/isolated');assert.equal(env.HOME,'/isolated/home');assert.equal(env.NUGET_PACKAGES,'/isolated/nuget');assert.equal(env.DOTNET_ROOT,'/usr/share/dotnet');for(const key of ['ACTIONS_RUNTIME_TOKEN','GITHUB_TOKEN','GH_TOKEN','GITHUB_ENV','ACTIONS_CACHE_URL','NODE_OPTIONS','DOTNET_STARTUP_HOOKS','GIT_CONFIG_COUNT'])assert.equal(env[key],undefined)})
test('staged changes, identical identity content drift, and changed HEAD/tree reject',()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'candidate-mutation-snapshot-'));try{writeFileSync(path.join(dir,'source.cs'),'initial literal');const original=snapshot(dir,['source.cs']);const identity={head:'a',tree:'b',expectedHead:'a',expectedTree:'b'};assert.doesNotThrow(()=>assertSnapshot(original,snapshot(dir,['source.cs']),identity,''));assert.throws(()=>assertSnapshot(original,original,identity,'M  source.cs'));writeFileSync(path.join(dir,'source.cs'),'changed staged or unstaged');assert.throws(()=>assertSnapshot(original,snapshot(dir,['source.cs']),identity,''));assert.throws(()=>assertSnapshot(original,original,{...identity,head:'new'},''));assert.throws(()=>assertSnapshot(original,original,{...identity,tree:'new'},''))}finally{rmSync(dir,{recursive:true,force:true})}})
test('ZIP identical bytes despite reversed enumeration and changed filesystem mtime',()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'candidate-mutation-zip-'));try{for(const name of ['b.txt','a.txt'])writeFileSync(path.join(dir,name),name);const entries=()=>['b.txt','a.txt'].map(name=>[name,readFileSync(path.join(dir,name))]);const a=deterministicZip(entries());utimesSync(path.join(dir,'a.txt'),new Date(12345),new Date(67890));const b=deterministicZip(entries().reverse());assert.deepEqual(a,b);assert.equal(a.readUInt32LE(0),0x04034b50);assert.equal(a.readUInt16LE(12),33);assert.throws(()=>deterministicZip([['../escape',Buffer.from('x')]]))}finally{rmSync(dir,{recursive:true,force:true})}})
test('score retains exact numerator denominator and existing rounded policy separately',()=>{const r=report();r.files[required[0]].mutants=[{status:'Timeout'},{status:'Survived'},{status:'NoCoverage'}];const result=validateReport(r,required,source,exit);assert.equal(result.scoreArithmetic.numerator,2);assert.equal(result.scoreArithmetic.denominator,4);assert.equal(result.scoreArithmetic.unroundedPercent,50);assert.equal(result.summary.score,50);assert.equal(result.summary.tested,3)})

test('literal official schema2 terminal inventory rejects missing/wrong schema and mixed pending statuses',()=>{for(const version of [undefined,2,'99']){const r=report();r.schemaVersion=version;assert.throws(()=>validateReport(r,required,source,exit))}for(const status of ['NotRun','Pending','unknown',undefined]){const r=report();r.files[required[0]].mutants.push({status});assert.throws(()=>validateReport(r,required,source,exit));const outside=report();outside.files['Outside.cs']={mutants:[{status}]};assert.throws(()=>validateReport(outside,required,source,exit))}const r=report();r.files[required[0]].mutants.push(...['Timeout','Survived','NoCoverage','CompileError','Ignored'].map(status=>({status})));const result=validateReport(r,required,source,exit);assert.equal(result.summary.counts.Killed,2);for(const status of ['Timeout','Survived','NoCoverage','CompileError','Ignored'])assert.equal(result.summary.counts[status],1);assert.equal(result.summary.tested,4)})

test('linked-path CLI reaches actual main and refuses invalid candidate input',()=>{const scratch=mkdtempSync(path.join(os.tmpdir(),'candidate-mutation-entry-'));try{const root=path.resolve(import.meta.dirname,'../..'),link=path.join(scratch,'repo-link');symlinkSync(root,link,process.platform==='win32'?'junction':'dir');const result=tool(process.execPath,[path.join(link,'eng/candidate-mutation.mjs')],{encoding:'utf8',env:buildEnvironment(process.env,path.join(scratch,'isolated'))});assert.notEqual(result.status,0);assert.match(result.stderr,/Invalid candidate\/project\/preset/)}finally{rmSync(scratch,{recursive:true,force:true})}})
