import test from 'node:test'
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {execFileSync, spawnSync} from 'node:child_process'
import {copyFileSync, chmodSync, realpathSync, mkdtempSync, mkdirSync, readFileSync, readdirSync, writeFileSync, rmSync, symlinkSync} from 'node:fs'
import path from 'node:path'
import {tmpdir} from 'node:os'
import {inputProblems, reuseProblems, definitionProblems} from '../platform-feed-reuse-policy.mjs'
import {findReusableFeed, githubClient, unpackFeed, consumeFeed, verifyMainInputs} from '../platform-feed-reuse.mjs'
import {fileClosure, platformIdentity, prepareContainer} from '../platform-feed-container.mjs'
import {verifyConsumedFeed} from '../platform-feed-consumption.mjs'
import {buildEnvironment} from '../platform-feed-environment.mjs'

// Literal package graph and invocation contract are independent of the producer implementation.
const digest = bytes => createHash('sha256').update(bytes).digest('hex')
const blob = bytes => createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex')
const repo = 'Harborline-Software/harborline-api', version = '0.0.0-alpha.0.h123456789abc'
const pin = {schemaVersion: 1, repository: 'Harborline-Software/harborline-platform', commit: 'a'.repeat(40),
  producers: {'Harborline.A': 'Harborline.A.dll'}}
const definitions = ['.github/workflows/platform-feed-producer.yml', '.github/workflows/verify.yml',
  '.github/actions/platform-feed/action.yml', 'eng/platform-feed-container.mjs', 'eng/platform-feed-reuse.mjs',
  'eng/platform-feed-reuse-policy.mjs', 'eng/platform-feed-profile.json', 'eng/build-local-feed.mjs',
  'eng/same-job-platform-feed.mjs', 'eng/exact-clone-platform-feed.mjs', 'eng/platform-feed-consumption.mjs',
  'eng/platform-feed-environment.mjs', 'eng/platform-feed-consumer-launch.mjs', 'eng/run-exact-clone.mjs', 'eng/platform-pin.json', 'global.json', 'nuget.config']
const tree = () => ({truncated: false, tree: definitions.map(name => ({path: name, sha: 'b'.repeat(40), mode: '100644', type: 'blob'}))})
const identity = () => ({schemaVersion: 1, profile: 'linux-x64-container-feed',
  platform: {...pin, tree: 'b'.repeat(40), history: 'c'.repeat(64), version}, packageGraph: {packedVersion: version},
  toolchain: {image: 'mcr.microsoft.com/dotnet/sdk@sha256:' + 'd'.repeat(64), sdk: '11.0.100-rc.1.26425.128',
    architecture: 'x64', node: 'e'.repeat(64), kernel: '6.8.0-fixture', containerRuntime: {Os: 'linux', Arch: 'amd64', Version: '29.0.0-fixture'}},
  producer: definitions.map(name => ({name, sha256: 'f'.repeat(64)})),
  restore: [{name: 'platform/A/obj/project.assets.json', sha256: '1'.repeat(64)}, {name: 'packages/provider/1.0/provider.dll', sha256: '2'.repeat(64)}],
  pack: {configuration: 'Release', network: 'none', restore: false, apiCodeExecuted: false}})
function zip(entries) {
  return Buffer.concat(entries.map(([name, bytes]) => {
    const header = Buffer.alloc(30)
    header.writeUInt32LE(0x04034b50); header.writeUInt32LE(bytes.length, 18); header.writeUInt32LE(bytes.length, 22)
    header.writeUInt16LE(Buffer.byteLength(name), 26)
    return Buffer.concat([header, Buffer.from(name), bytes])
  }))
}
const files = () => [{name: `Harborline.A.${version}.nupkg`, bytes: zip([
  ['Harborline.A.nuspec', Buffer.from(`<package><metadata><id>Harborline.A</id><version>${version}</version><dependencies /></metadata></package>`)],
  ['lib/net11.0/Harborline.A.dll', Buffer.from('managed fixture bytes')],
  ['lib/net11.0/Harborline.A.xml', Buffer.from('<doc>unused documentation</doc>')]])},
{name: 'packed-version.props', bytes: Buffer.from(`<!-- Generated by eng/build-local-feed.mjs; .feed is gitignored. -->\n<Project>\n  <PropertyGroup>\n    <HarborlinePackedVersion>${version}</HarborlinePackedVersion>\n  </PropertyGroup>\n</Project>\n`)}]
const bundle = (input = identity()) => Buffer.from(JSON.stringify({schemaVersion: 1, identity: input,
  closure: [{id: 'Harborline.A', version, assemblies: ['Harborline.A.dll'], dependencies: []}],
  files: files().map(({name, bytes}) => ({name, size: bytes.length, sha256: digest(bytes), base64: bytes.toString('base64')}))}))
const now = Date.parse('2026-10-03T12:00:00Z')
test('build children receive no metadata/runtime token while unrelated build environment stays intact', () => {
  const input = {GH_TOKEN: 'synthetic-one', GITHUB_TOKEN: 'synthetic-two', ACTIONS_RUNTIME_TOKEN: 'synthetic-three',
    GH_ENTERPRISE_TOKEN: 'synthetic-enterprise-one', GITHUB_ENTERPRISE_TOKEN: 'synthetic-enterprise-two',
    ACTIONS_ID_TOKEN_REQUEST_TOKEN: 'synthetic-four', NUGET_PACKAGES: '/scratch/packages', HARBORLINE_FEED_NO_RESTORE: '1'}
  assert.deepEqual(buildEnvironment(input), {NUGET_PACKAGES: '/scratch/packages', HARBORLINE_FEED_NO_RESTORE: '1'})
  assert.equal(input.GH_TOKEN, 'synthetic-one', 'metadata parent retains its token')
})
test('actual restore consumption binds package archives and selected/extracted bytes in a fresh scratch cache', t => {
  const root = mkdtempSync(path.join(tmpdir(), 'verified-feed-consumption-'))
  t.after(() => rmSync(root, {recursive: true, force: true}))
  const clone = path.join(root, 'clone'), packages = path.join(root, 'nuget-packages')
  const packageFolder = path.join(packages, `harborline.a/${version}`)
  const feed = path.join(clone, '.feed'), assetFolder = path.join(clone, 'app/obj')
  for (const folder of [feed, assetFolder, path.join(packageFolder, 'lib/net11.0')]) mkdirSync(folder, {recursive: true})
  const fixtureFiles = files(), raw = bundle(), bundlePath = path.join(root, 'authenticated-bundle.json')
  writeFileSync(bundlePath, raw)
  for (const file of fixtureFiles) writeFileSync(path.join(feed, file.name), file.bytes)
  const archivePath = path.join(packageFolder, `harborline.a.${version}.nupkg`)
  const dllPath = path.join(packageFolder, 'lib/net11.0/Harborline.A.dll')
  writeFileSync(archivePath, fixtureFiles[0].bytes); writeFileSync(dllPath, 'managed fixture bytes')
  const asset = () => ({packageFolders: {[packages + path.sep]: {}},
    libraries: {[`Harborline.A/${version}`]: {type: 'package', path: `harborline.a/${version}`}},
    targets: {'net11.0': {[`Harborline.A/${version}`]: {compile: {'lib/net11.0/Harborline.A.dll': {}}, runtime: {'lib/net11.0/Harborline.A.dll': {}}}}}})
  const assetsPath = path.join(assetFolder, 'project.assets.json')
  const ownerProject = path.join(clone, 'app/Harborline.Api.Client.csproj')
  const contractProject = path.join(clone, 'src/Harborline.Api.Contracts/Harborline.Api.Contracts.csproj')
  mkdirSync(path.dirname(contractProject), {recursive: true})
  writeFileSync(ownerProject, '<Project><ItemGroup><ProjectReference Include="../src/Harborline.Api.Contracts/Harborline.Api.Contracts.csproj" /></ItemGroup></Project>')
  writeFileSync(contractProject, '<Project><PropertyGroup><PackageId>Harborline.Api.Contracts</PackageId></PropertyGroup></Project>')
  const reset = () => {writeFileSync(assetsPath, JSON.stringify(asset())); writeFileSync(bundlePath, raw);
    writeFileSync(archivePath, fixtureFiles[0].bytes); writeFileSync(dllPath, 'managed fixture bytes');
    for (const file of fixtureFiles) writeFileSync(path.join(feed, file.name), file.bytes)}
  reset()
  const options = {clone, packages, bundlePath, bundleDigest: digest(raw), pin}
  const result = verifyConsumedFeed(options)
  assert.equal(result.dependencyBytesVerified, true)
  assert.equal(result.apiValidationReused, false)
  assert.deepEqual(result.packages, [{package: `Harborline.A/${version}`, archiveSha256: digest(fixtureFiles[0].bytes), selectedFiles: 2}])
  const projectReference = () => {
    const value = asset()
    value.project = {restore: {projectPath: ownerProject}}
    value.libraries['Harborline.Api.Contracts/0.1.0-preview.1'] = {type: 'project',
      path: '../src/Harborline.Api.Contracts/Harborline.Api.Contracts.csproj',
      msbuildProject: '../src/Harborline.Api.Contracts/Harborline.Api.Contracts.csproj'}
    return value
  }
  writeFileSync(assetsPath, JSON.stringify(projectReference()))
  assert.deepEqual(verifyConsumedFeed(options).packages, result.packages, 'legitimate API project references still compile freshly')
  // XML forbids a comment inside an element name. Removing it must not create PackageId authority.
  const splitTag = projectReference()
  const splitProject = '../src/Harborline.Api.Contracts/Different.csproj'
  splitTag.libraries['Harborline.Api.Contracts/0.1.0-preview.1'].path = splitProject
  splitTag.libraries['Harborline.Api.Contracts/0.1.0-preview.1'].msbuildProject = splitProject
  writeFileSync(path.join(path.dirname(contractProject), 'Different.csproj'),
    '<Project><Package<!-- removed -->Id>Harborline.Api.Contracts</PackageId></Project>')
  writeFileSync(assetsPath, JSON.stringify(splitTag))
  assert.throws(() => verifyConsumedFeed(options), /differs from source identity/)
  writeFileSync(contractProject, '<Project><!-- <PackageId>Harborline.Wrong</PackageId> --><PackageId>Harborline.Api.Contracts</PackageId></Project>')
  writeFileSync(assetsPath, JSON.stringify(projectReference()))
  assert.equal(verifyConsumedFeed(options).dependencyBytesVerified, true, 'ordinary comments remain inert')
  const changes = [
    () => writeFileSync(archivePath, 'older same-version cached archive'),
    () => writeFileSync(dllPath, 'older or changed extracted assembly'),
    () => writeFileSync(path.join(feed, fixtureFiles[0].name), 'changed materialized feed'),
    () => writeFileSync(bundlePath, Buffer.concat([raw, Buffer.from(' ')])),
    () => {const value = asset(); value.packageFolders = {[path.join(root, 'global-cache')]: {}}; writeFileSync(assetsPath, JSON.stringify(value))},
    () => {const value = asset(); value.libraries[`Harborline.A/${version}`].path = '../escape'; writeFileSync(assetsPath, JSON.stringify(value))},
    () => {const value = asset(); value.targets['net11.0'][`Harborline.A/${version}`].compile = {'../unsafe.dll': {}}; writeFileSync(assetsPath, JSON.stringify(value))},
    () => {const value = asset(); value.targets['net11.0'][`Harborline.A/${version}`].resource = {'lib/net11.0/Harborline.A.xml': {}}; writeFileSync(assetsPath, JSON.stringify(value))},
    () => {const value = asset(); value.libraries['Harborline.Unapproved/1.0'] = {type: 'package', path: 'harborline.unapproved/1.0'}; writeFileSync(assetsPath, JSON.stringify(value))},
    () => {const value = asset(); value.targets = {}; writeFileSync(assetsPath, JSON.stringify(value))},
    () => writeFileSync(assetsPath, JSON.stringify({packageFolders: {[packages]: {}}, libraries: {}, targets: {}})),
    () => {const value = asset(); value.libraries[`Harborline.A/${version}`].type = 'project'; writeFileSync(assetsPath, JSON.stringify(value))},
    () => {const value = projectReference(); value.libraries['Harborline.Api.Contracts/0.1.0-preview.1'].path = '../../escape.csproj'; writeFileSync(assetsPath, JSON.stringify(value))},
    () => {const value = projectReference(); value.libraries['Harborline.Api.Contracts/0.1.0-preview.1'].msbuildProject = 'other.csproj'; writeFileSync(assetsPath, JSON.stringify(value))},
    () => {const value = projectReference(); value.libraries['Harborline.Unknown/1.0'] = value.libraries['Harborline.Api.Contracts/0.1.0-preview.1']; delete value.libraries['Harborline.Api.Contracts/0.1.0-preview.1']; writeFileSync(assetsPath, JSON.stringify(value))},
  ]
  for (const change of changes) {reset(); change(); assert.throws(() => verifyConsumedFeed(options))}
  reset()
  assert.throws(() => verifyConsumedFeed({...options, packages: path.join(root, 'global-cache')}), /scratch-owned/)
  // The exact-clone step uses its own root before restore and gates compilation on proof.
  const runner = readFileSync(path.resolve(import.meta.dirname, '../run-exact-clone.mjs'), 'utf8')
  assert.ok(runner.indexOf("process.env.NUGET_PACKAGES = path.join(scratch, 'nuget-packages')") < runner.indexOf("run('dotnet-restore'"))
  assert.ok(runner.indexOf("run('platform-feed-consumption'") < runner.indexOf("run('dotnet-build'"))
})

const run = () => ({id: 123, run_attempt: 1, repository: {full_name: repo}, head_repository: {full_name: repo},
  path: '.github/workflows/platform-feed-producer.yml', head_branch: 'main', head_sha: 'a'.repeat(40),
  event: 'workflow_dispatch', status: 'completed', conclusion: 'success', run_started_at: '2026-10-03T10:00:00Z'})
const job = () => ({name: 'produce-linux', run_id: 123, run_attempt: 1, status: 'completed', conclusion: 'success',
  started_at: '2026-10-03T10:01:00Z', completed_at: '2026-10-03T10:10:00Z',
  steps: [{name: 'Build isolated feed', status: 'completed', conclusion: 'success'}]})
const archive = Buffer.from('independently bound fixture archive bytes')
const artifact = () => ({id: 789, name: 'platform-feed-linux-123', expired: false,
  workflow_run: {id: 123, head_sha: 'a'.repeat(40)}, created_at: '2026-10-03T10:09:00Z', digest: `sha256:${digest(archive)}`})
const binding = () => ({expected: identity(), observed: identity(), run: run(), job: job(), artifact: artifact(), archive, now,
  trustedDefinitionsMatch: true, sourceOnProtectedMain: true})
const trusted = () => ({mainSha: 'a'.repeat(40), tree: tree(), pin})
function apiFixture(edit = () => {}) {
  const state = {run: run(), job: job(), artifact: artifact(), source: tree(), main: tree(), bytes: archive,
    raw: bundle(), ancestry: 'identical', count: 1, jobsCount: 1}
  edit(state)
  return {state, api: async (endpoint, binary) => {
    if (endpoint.includes('/workflows/')) return {workflow_runs: [{id: 123}]}
    if (endpoint.endsWith('/runs/123')) return state.run
    if (endpoint.includes('/artifacts?')) return {total_count: state.count, artifacts: [state.artifact]}
    if (endpoint.includes('/jobs?')) return {total_count: state.jobsCount, jobs: [state.job]}
    if (endpoint.includes('/git/trees/')) return state.source
    if (endpoint.includes('/compare/')) return {status: state.ancestry}
    if (binary) return state.bytes
    throw new Error('unexpected fixture endpoint')
  }}
}

test('verified immutable dependency feed preserves literal bytes without reusing an API verdict', async () => {
  const fixture = apiFixture()
  const result = await findReusableFeed({api: fixture.api, trusted: trusted(), expected: identity(), unpack: () => fixture.state.raw, now})
  assert.deepEqual(result.files, files())
  assert.equal(result.producerRun, 123)
  assert.equal(result.producerAttempt, 1)
  assert.equal(result.archiveDigest, `sha256:${digest(archive)}`)
  assert.equal(result.artifactReuse, true)
  assert.equal(result.validationReuse, false)
})

test('profile, image, SDK, history, restore bytes and producer changes deny a match', () => {
  assert.deepEqual(inputProblems(identity()), [])
  const mutations = [input => {input.profile = 'windows'}, input => {input.toolchain.image += 'x'},
    input => {input.toolchain.sdk = '11.0.101'}, input => {input.toolchain.architecture = 'arm64'},
    input => {input.platform.history = '0'.repeat(64)}, input => {input.restore[0].sha256 = '0'.repeat(64)},
    input => {input.producer[0].sha256 = '0'.repeat(64)}, input => {input.toolchain.node = '0'.repeat(64)},
    input => {input.toolchain.kernel = 'changed-kernel'}, input => {input.pack.network = 'bridge'},
    input => {input.pack.apiCodeExecuted = true}, input => {input.restore = []}, input => {input.producer = []}]
  for (const mutate of mutations) {
    const value = binding(); mutate(value.observed)
    assert.ok(reuseProblems(value).length, 'every declared identity change must refuse')
  }
})

test('foreign, PR, failed, skipped, expired, old-attempt and unbound producer evidence is denied before unpack', async () => {
  const mutations = [s => {s.run.repository.full_name = 'attacker/repo'}, s => {s.run.head_repository.full_name = 'attacker/repo'},
    s => {s.run.event = 'pull_request'}, s => {s.run.event = 'schedule'}, s => {s.run.event = 'push'}, s => {s.run.path = '.github/workflows/verify.yml'}, s => {s.run.head_branch = 'feature'},
    s => {s.run.conclusion = 'failure'}, s => {s.job.conclusion = 'skipped'}, s => {s.job.steps[0].conclusion = 'cancelled'},
    s => {s.artifact.expired = true}, s => {s.artifact.workflow_run.head_sha = 'f'.repeat(40)},
    s => {s.bytes = Buffer.from('changed archive')}, s => {s.run.run_attempt = 2},
    s => {s.run.run_attempt = 2; s.job.run_attempt = 2; s.run.run_started_at = '2026-10-03T11:00:00Z'},
    s => {s.artifact.created_at = '2026-09-01T10:09:00Z'}, s => {s.ancestry = 'diverged'},
    s => {s.count = 101}, s => {s.jobsCount = 101}]
  for (const mutate of mutations) {
    const fixture = apiFixture(mutate); let unpacked = false
    const result = await findReusableFeed({api: fixture.api, trusted: trusted(), expected: identity(), now,
      unpack: () => {unpacked = true; return fixture.state.raw}})
    assert.equal(result, null)
    assert.equal(unpacked, false, 'metadata rejection must precede artifact parsing')
  }
})

test('artifact fields cannot supply trust policy or conceal changed producer definitions', async () => {
  for (const name of definitions) {
    const fixture = apiFixture(s => {s.source.tree.find(file => file.path === name).sha = 'e'.repeat(40)})
    assert.equal(await findReusableFeed({api: fixture.api, trusted: trusted(), expected: identity(), now,
      unpack: () => Buffer.from(JSON.stringify({...JSON.parse(bundle()), trusted: true, sourceOnProtectedMain: true, policy: 'allow'}))}), null, name)
  }
  assert.ok(definitionProblems({trustedTree: {...tree(), truncated: true}, sourceTree: tree(), paths: definitions}).length)
})

test('wrong inventory, package bytes, version and dependency closure refuse even with authenticated transport', async () => {
  const mutations = [value => {value.files.pop()}, value => {value.files[0].base64 = Buffer.from('tampered').toString('base64')},
    value => {value.files[0].name = '../escape.nupkg'}, value => {value.closure[0].version = '9.0.0'},
    value => {value.identity.platform.version = '9.0.0'}, value => {value.files.push(value.files[0])}]
  for (const mutate of mutations) {
    const fixture = apiFixture(), value = JSON.parse(bundle()); mutate(value)
    const operation = findReusableFeed({api: fixture.api, trusted: trusted(), expected: identity(), now,
      unpack: () => Buffer.from(JSON.stringify(value))})
    if (value.identity.platform.version !== version) assert.equal(await operation, null)
    else await assert.rejects(operation)
  }
})

test('GitHub redirect drops credentials; forbidden endpoints and unsafe redirects refuse', async () => {
  const calls = []
  const client = githubClient('synthetic-credential', async (url, options) => {
    calls.push({url, options})
    if (calls.length === 1) return new Response(null, {status: 302, headers: {location: 'https://storage.example/artifact'}})
    return new Response(archive)
  })
  assert.deepEqual(await client(`/repos/${repo}/actions/artifacts/789/zip`, true), archive)
  assert.equal(calls[1].options.headers, undefined)
  assert.equal(calls[1].options.redirect, 'error')
  await assert.rejects(client('/repos/attacker/repo/actions/artifacts/789/zip', true))
  for (const target of ['http://storage.example/artifact', 'https://user:password@storage.example/artifact']) {
    await assert.rejects(githubClient('synthetic', async () => new Response(null,
      {status: 302, headers: {location: target}}))(`/repos/${repo}/actions/artifacts/789/zip`, true))
  }
})

test('archive reader accepts only one bounded named data entry and never extracts or executes', () => {
  const python = realpathSync(execFileSync(process.platform === 'win32' ? 'python' : 'python3', ['-I', '-c', 'import sys;print(sys.executable)'], {encoding: 'utf8'}).trim())
  const make = names => execFileSync(python, ['-c',
    "import io,sys,zipfile,json\nb=io.BytesIO()\nwith zipfile.ZipFile(b,'w') as z:\n for n in json.loads(sys.argv[1]): z.writestr(n,'fixture')\nsys.stdout.buffer.write(b.getvalue())", JSON.stringify(names)], {stdio: 'pipe'})
  const decode = bytes => unpackFeed(bytes, `sha256:${digest(bytes)}`, {python})
  assert.equal(decode(make(['feed-bundle.json'])).toString(), 'fixture')
  for (const names of [['../execute.py'], ['feed-bundle.json', '../execute.py'], ['feed-bundle.json', 'feed-bundle.json']])
    assert.throws(() => decode(make(names)))
  const archive = make(['feed-bundle.json'])
  assert.throws(() => unpackFeed(archive, 'sha256:' + '0'.repeat(64)), /digest differs/)
  const directory = mkdtempSync(path.join(tmpdir(), 'candidate-python-shadow-')), previousCwd = process.cwd(), previousPath = process.env.PYTHONPATH
  const marker = path.join(directory, 'candidate-module-executed')
  const priorSearchPath = process.env.PATH
  // A real executable on PATH rejects Python flags; bare lookup would fail this test.
  for (const name of (process.platform === 'win32' ? ['python.exe', 'python3.exe'] : ['python', 'python3']))
    copyFileSync(process.execPath, path.join(directory, name))
  writeFileSync(path.join(directory, 'zipfile.py'), `open(${JSON.stringify(marker)},'w').write('executed')\nclass ZipFile:\n def __init__(self,*args): pass\n def __enter__(self): return self\n def __exit__(self,*args): pass\n def namelist(self): return ['feed-bundle.json']\n def getinfo(self,*args): return type('Info',(),{'file_size':6})()\n def read(self,*args): return b'forged'\n`)
  try {
    process.chdir(directory); process.env.PYTHONPATH = directory
    process.env.PATH = directory + path.delimiter + priorSearchPath
    assert.throws(() => unpackFeed(archive, `sha256:${digest(archive)}`, {python: ''}), /trusted archive interpreter unavailable/)
    assert.equal(decode(archive).toString(), 'fixture', 'authenticated ZIP entry is authoritative even with candidate shadow modules')
    assert.equal(readdirSync(directory).includes('candidate-module-executed'), false, 'candidate module never executes')
  } finally {
    process.chdir(previousCwd)
    process.env.PATH = priorSearchPath
    if (previousPath === undefined) delete process.env.PYTHONPATH; else process.env.PYTHONPATH = previousPath
    rmSync(directory, {recursive: true, force: true})
  }
})

function sourceFixture(t) {
  const directory = mkdtempSync(path.join(tmpdir(), 'feed-trust-fixture-'))
  t.after(() => rmSync(directory, {recursive: true, force: true}))
  const mainTree = tree()
  for (const name of definitions) {
    const file = path.join(directory, name); mkdirSync(path.dirname(file), {recursive: true})
    const bytes = Buffer.from(name === 'eng/platform-pin.json' ? JSON.stringify(pin) : `reviewed:${name}`)
    writeFileSync(file, bytes); mainTree.tree.find(item => item.path === name).sha = blob(bytes)
  }
  const fixture = apiFixture()
  const api = async (endpoint, binary) => endpoint.endsWith('/branches/main') ? {protected: true, commit: {sha: 'a'.repeat(40)}}
    : endpoint.includes('/git/trees/') ? mainTree : endpoint.includes('/compare/') ? {status: 'identical'} : fixture.api(endpoint, binary)
  return {directory, api, mainTree, fixture}
}

test('trusted main definitions and protected platform ancestry are independently required', async t => {
  const source = sourceFixture(t)
  assert.equal((await verifyMainInputs({api: source.api, apiRoot: source.directory})).mainSha, 'a'.repeat(40))
  await assert.rejects(verifyMainInputs({apiRoot: source.directory, api: async endpoint => endpoint.endsWith('/branches/main')
    ? {protected: false, commit: {sha: 'a'.repeat(40)}} : source.api(endpoint)}))
  writeFileSync(path.join(source.directory, 'eng/platform-feed-reuse-policy.mjs'), 'candidate-modified policy')
  await assert.rejects(verifyMainInputs({api: source.api, apiRoot: source.directory}))
})

test('consumer publishes only independently verified bytes; every unavailable or mismatched case requests fresh fallback', async t => {
  const source = sourceFixture(t); let published = 0, prepared = 0
  const options = {api: source.api, apiRoot: source.directory, platform: '/fixture-platform', now,
    host: {os: 'linux', architecture: 'x64'}, env: {GITHUB_REPOSITORY: repo, GITHUB_JOB: 'verify-linux', HARBORLINE_VERIFY_LANE: 'host'},
    prepare: () => {prepared++; return {input: identity()}}, unpack: () => bundle(),
    publish: value => {assert.deepEqual(value, files()); published++; return {path: '/fixture/handoff', sha256: 'e'.repeat(64)}}}
  const result = await consumeFeed(options)
  assert.equal(result.reused, true); assert.equal(published, 1); assert.equal(result.validationReuse, false)
  for (const change of [{host: {os: 'win32', architecture: 'x64'}}, {env: {...options.env, GITHUB_JOB: 'verify-windows-hosted'}},
    {prepare: () => {throw new Error('Docker unavailable')}}, {api: async () => {throw new Error('metadata unavailable')}},
    {unpack: () => Buffer.from('malformed artifact')}, {unpack: () => bundle({...identity(), restore: []})}]) {
    const before = published; assert.equal((await consumeFeed({...options, ...change})).reused, false); assert.equal(published, before)
  }
  const beforePrepare = prepared
  const empty = await consumeFeed({...options, api: async endpoint => endpoint.includes('/workflows/')
    ? {workflow_runs: []} : source.api(endpoint)})
  assert.equal(empty.reused, false); assert.equal(prepared, beforePrepare, 'no successful producer means no Docker startup')
})

test('byte closure uses literal SHA-256 and refuses symlink inputs', t => {
  const root = mkdtempSync(path.join(tmpdir(), 'feed-byte-closure-'))
  t.after(() => rmSync(root, {recursive: true, force: true}))
  writeFileSync(path.join(root, 'provider.dll'), 'abc')
  assert.deepEqual(fileClosure(root, 'packages'), [{name: 'packages/provider.dll',
    sha256: 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'}])
  writeFileSync(path.join(root, 'provider.dll'), 'changed')
  assert.notEqual(fileClosure(root)[0].sha256, 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad')
  const target = path.join(root, 'nested'); mkdirSync(target)
  symlinkSync(target, path.join(root, 'linked'), process.platform === 'win32' ? 'junction' : 'dir')
  assert.throws(() => fileClosure(root), /symlink/)
})

test('real container planner isolates mounts, independently restores every project and detects post-pack input drift', t => {
  const source = sourceFixture(t), platform = path.join(source.directory, '.platform')
  mkdirSync(platform)
  const git = (...args) => execFileSync('git', ['-c', `safe.directory=${platform}`, '-C', platform, ...args], {encoding: 'utf8'}).trim()
  git('init', '-q'); git('config', 'user.name', 'Feed fixture'); git('config', 'user.email', 'fixture@example.invalid')
  writeFileSync(path.join(platform, '.gitignore'), 'obj/\nbin/\n')
  writeFileSync(path.join(platform, 'A.csproj'), '<Project Sdk="Microsoft.NET.Sdk" />')
  git('add', '.'); git('commit', '-qm', 'literal fixture')
  mkdirSync(path.join(platform, 'bin')); writeFileSync(path.join(platform, 'bin/old.dll'), 'ambient old build')
  const selectedPin = {...pin, commit: git('rev-parse', 'HEAD')}
  const profile = {profile: 'linux-x64-container-feed', architecture: 'x64', image: identity().toolchain.image, sdk: '11.0.100-rc.1.26425.128'}
  writeFileSync(path.join(source.directory, 'eng/platform-feed-profile.json'), JSON.stringify(profile))
  const calls = []; let changeDuringPack = false
  const mockDocker = (executable, args) => {
    assert.equal(executable, 'docker'); calls.push(args)
    if (args[0] === 'version') return JSON.stringify({Os: 'linux', Arch: 'amd64', Version: '29.0.0-fixture'})
    if (args[0] === 'pull') return ''
    if (args[0] === 'image') return 'linux/amd64'
    const command = args.slice(args.lastIndexOf(profile.image) + 1)
    const mount = target => args.find(value => value.startsWith('type=bind,source=') && value.endsWith(`,target=${target}`))
      .slice('type=bind,source='.length, -(`,target=${target}`.length))
    if (command[0] === 'dotnet' && command[1] === '--version') return profile.sdk
    if (command.includes('--dry-run')) return JSON.stringify({packedVersion: version,
      commands: [['pack', '/platform/A.csproj', '-p:HarborlinePackedVersion=' + version]]})
    if (command[0] === 'dotnet' && command[1] === 'restore') {
      assert.notEqual(mount('/platform'), platform, 'pack owns a fresh clone rather than caller ignored outputs')
      assert.equal(readdirSync(mount('/platform')).includes('bin'), false, 'ambient ignored build directory was not copied')
      assert.equal(args[args.indexOf('--network') + 1], 'bridge')
      mkdirSync(path.join(mount('/platform'), 'obj'), {recursive: true})
      writeFileSync(path.join(mount('/platform'), 'obj/project.assets.json'), JSON.stringify({project: {restore: {projectPath: '/platform/A.csproj', packagesPath: '/packages'}}}))
      writeFileSync(path.join(mount('/platform'), 'obj/restore-generated-extra.txt'), 'abc')
      writeFileSync(path.join(mount('/packages'), 'provider.dll'), 'abc')
      return ''
    }
    assert.deepEqual(command, ['/tool/node', '/tool/eng/build-local-feed.mjs'])
    assert.equal(args[args.indexOf('--network') + 1], 'none')
    assert.ok(args.includes('HARBORLINE_FEED_NO_RESTORE=1'))
    const feed = path.join(mount('/output'), '.feed')
    mkdirSync(feed, {recursive: true})
    for (const file of files()) writeFileSync(path.join(feed, file.name), file.bytes)
    if (changeDuringPack === 'package') writeFileSync(path.join(mount('/packages'), 'provider.dll'), 'changed after restore')
    if (changeDuringPack === 'generated') writeFileSync(path.join(mount('/platform'), 'obj/restore-generated-extra.txt'), 'changed after restore')
    return ''
  }
  const stages = []
  const prepared = prepareContainer({apiRoot: source.directory, platform, pin: selectedPin, run: mockDocker,
    observe: (stage, details) => {stages.push({stage, ...details}); if (stage === 'container-builder-plan') throw Error('private-observer-error')},
    host: {os: 'linux', architecture: 'x64', uid: 1001, gid: 1001, kernel: '6.8.0-fixture'}})
  t.after(() => rmSync(prepared.directory, {recursive: true, force: true}))
  assert.deepEqual(prepared.pack().sort((a, b) => a.name.localeCompare(b.name)), files().sort((a, b) => a.name.localeCompare(b.name)))
  assert.deepEqual(stages.slice(0, 14).map(item => item.stage), ['host-profile', 'checkout-policy', 'source-identity',
    'isolated-platform-clone', 'isolated-platform-checkout', 'isolated-platform-identity', 'reviewed-tool-copy',
    'container-runtime-version', 'container-image-pull', 'container-image-platform', 'container-sdk-version',
    'container-builder-plan', 'container-builder-plan-validation', 'container-project-restore'])
  assert.deepEqual(stages.find(item => item.stage === 'container-project-restore'), {stage: 'container-project-restore', projectIndex: 0, projectCount: 1})
  assert.deepEqual(stages.slice(-2).map(item => item.stage), ['container-builder-pack', 'post-pack-input-closure'])
  assert.doesNotMatch(JSON.stringify(stages), /private-|\/platform|GH_TOKEN|https:/)
  assert.equal(readFileSync(path.join(platform, 'bin/old.dll'), 'utf8'), 'ambient old build', 'caller output preserved')
  assert.equal(prepared.input.restore.find(file => file.name === 'packages/provider.dll').sha256,
    'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad')
  assert.equal(prepared.input.restore.find(file => file.name === 'platform/obj/restore-generated-extra.txt').sha256,
    'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad')
  for (const args of calls.filter(args => args[0] === 'run')) {
    assert.equal(args.filter(value => value === '--init').length, 1); assert.ok(args.includes('--read-only')); assert.ok(args.includes('--cap-drop=ALL'))
    assert.ok(args.includes('HARBORLINE_FEED_OUTPUT_ROOT=/output/.feed'))
    assert.equal(args.some(value => value.endsWith(',target=/tool/.feed')), false, 'owned feed child is not a mount root')
    assert.equal(args.some(value => value.includes('GH_TOKEN') || value.includes('GITHUB_TOKEN')), false)
    assert.equal(args.includes(`type=bind,source=${source.directory},target=/api`), false)
  }
  changeDuringPack = 'generated'
  assert.throws(() => prepared.pack(), /changed input closure/)
  changeDuringPack = 'package'
  assert.throws(() => prepared.pack(), /changed input closure/)
  const beforeTag = platformIdentity(platform, selectedPin).history
  git('tag', 'v0.0.0-fixture')
  assert.notEqual(platformIdentity(platform, selectedPin).history, beforeTag)
  writeFileSync(path.join(platform, 'A.csproj'), 'changed tracked project')
  assert.throws(() => platformIdentity(platform, selectedPin), /clean/)
})

test('workflow keeps every fresh API gate, dormant Linux prototype, read-only producer and a fixed dependency-only upload', () => {
  const root = path.resolve(import.meta.dirname, '../..')
  const workflow = readFileSync(path.join(root, '.github/workflows/platform-feed-producer.yml'), 'utf8')
  assert.match(workflow, /contents: read/)
  assert.match(workflow, /workflow_dispatch:/)
  assert.equal(/schedule:|push:/.test(workflow), false)
  assert.equal(/(?:contents|actions|checks|packages|id-token): write/.test(workflow), false)
  assert.equal(/pull_request:|pull_request_target:/.test(workflow), false)
  assert.match(workflow, /ref: \$\{\{ github\.workflow_sha \}\}/)
  assert.match(workflow, /persist-credentials: false/)
  assert.match(workflow, /path: \.claude\/platform-feed-producer\/feed-bundle\.json/)
  const action = readFileSync(path.join(root, '.github/actions/platform-feed/action.yml'), 'utf8')
  assert.ok(action.indexOf('id: feed_tools') < action.indexOf('name: Test the feed contract'))
  assert.match(action, /HARBORLINE_FEED_PYTHON: \$\{\{ steps\.feed_tools\.outputs\.python \}\}/)
  assert.match(action, /eng\/platform-feed-consumer-launch\.mjs/)
  assert.match(action, /TRUSTED_FEED_ACTION_PATH: \$\{\{ github\.action_path \}\}/)
  assert.match(action, /"\$trusted_root\/eng\/platform-feed-consumer-launch\.mjs"/)
  assert.ok(action.indexOf('id: feed_reuse') < action.indexOf('name: Test the feed contract'))
  assert.equal(action.slice(action.indexOf('name: Build the local package feed')).includes('GH_TOKEN: ${{ github.token }}'), false)
  assert.match(action, /"\$FEED_NODE" eng\/build-local-feed\.mjs/)
  assert.match(action, /"\$FEED_NODE" eng\/same-job-platform-feed\.mjs build/)
  const verify = readFileSync(path.join(root, '.github/workflows/verify.yml'), 'utf8')
  assert.equal((verify.match(/(?:cross-run-reuse|same-job-handoff): 'true'/g) ?? []).length, 0)
  assert.match(action, /cross-run-reuse:[\s\S]*?default: 'false'/)
  assert.match(action, /same-job-handoff:[\s\S]*?default: 'false'/)
  assert.match(verify.slice(verify.indexOf('  verify-linux:'), verify.indexOf('  verify-windows:')),
    /uses: Harborline-Software\/harborline-api\/\.github\/actions\/platform-feed@main/)
  assert.match(verify, /run: bash eng\/verify\.sh/)
})

test('composed action executes fresh fallback and propagates its failure; artifact success never executes a second pack', t => {
  const root = path.resolve(import.meta.dirname, '../..')
  const source = readFileSync(path.join(root, '.github/actions/platform-feed/action.yml'), 'utf8')
  const run = source.slice(source.lastIndexOf('      run: |') + '      run: |'.length)
    .trimStart().split('\n').map(line => line.replace(/^        /, '')).join('\n')
  const directory = mkdtempSync(path.join(tmpdir(), 'feed-action-contract-'))
  t.after(() => rmSync(directory, {recursive: true, force: true}))
  const bash = process.platform === 'win32' ? 'C:/Program Files/Git/bin/bash.exe' : '/bin/bash'
  const cases = [
    {cross: 'false', same: 'false', reuse: 2, fresh: 0, status: 0, calls: ['eng/build-local-feed.mjs']},
    {cross: 'false', same: 'true', reuse: 2, fresh: 0, status: 0, calls: ['eng/same-job-platform-feed.mjs build /fixture/platform']},
    {cross: 'true', same: 'true', reuse: 0, fresh: 1, status: 0, calls: []},
    {cross: 'true', same: 'true', reuse: 2, fresh: 0, status: 0,
      calls: ['eng/same-job-platform-feed.mjs build /fixture/platform']},
    {cross: 'true', same: 'false', reuse: 2, fresh: 1, status: 1,
      calls: ['eng/build-local-feed.mjs']},
    {cross: 'invalid', same: 'true', reuse: 0, fresh: 0, status: 1, calls: []},
    {cross: 'true', same: 'invalid', reuse: 0, fresh: 0, status: 1, calls: []},
  ]
  for (const fixture of cases) {
    const record = path.join(directory, 'calls.txt'); writeFileSync(record, '')
    const harness = 'set -eo pipefail\nnode() { printf "%s\\n" "$*" >> "$TEST_FEED_RECORD"; if [[ "$1" = eng/platform-feed-reuse.mjs ]]; then [[ -n "${GH_TOKEN:-}" ]] || return 88; return "$TEST_REUSE_STATUS"; else [[ -z "${GH_TOKEN:-}${GITHUB_TOKEN:-}${GH_ENTERPRISE_TOKEN:-}${GITHUB_ENTERPRISE_TOKEN:-}${ACTIONS_RUNTIME_TOKEN:-}${ACTIONS_ID_TOKEN_REQUEST_TOKEN:-}" ]] || return 91; return "$TEST_FRESH_STATUS"; fi; }\n'
    const result = spawnSync(bash, ['-c', harness + run], {encoding: 'utf8', timeout: 10000, env: {...process.env,
      FEED_NODE: 'node', FEED_REUSED: fixture.reuse === 0 ? 'true' : 'false', CROSS_RUN_REUSE: fixture.cross, SAME_JOB_HANDOFF: fixture.same, HARBORLINE_PLATFORM_REPO: '/fixture/platform',
      GH_TOKEN: 'synthetic-metadata-only', GITHUB_TOKEN: 'synthetic-build-forbidden',
      GH_ENTERPRISE_TOKEN: 'synthetic-enterprise-one', GITHUB_ENTERPRISE_TOKEN: 'synthetic-enterprise-two',
      ACTIONS_RUNTIME_TOKEN: 'synthetic-runtime', ACTIONS_ID_TOKEN_REQUEST_TOKEN: 'synthetic-identity',
      TEST_FEED_RECORD: record.replaceAll('\\', '/'), TEST_REUSE_STATUS: String(fixture.reuse), TEST_FRESH_STATUS: String(fixture.fresh)}})
    assert.equal(result.status, fixture.status, result.stderr)
    assert.deepEqual(readFileSync(record, 'utf8').trim().split('\n').filter(Boolean), fixture.calls)
  }
})

test('composed reuse launches pinned Node after candidate PATH and function shadowing', t => {
  const root = path.resolve(import.meta.dirname, '../..')
  const source = readFileSync(path.join(root, '.github/actions/platform-feed/action.yml'), 'utf8')
  const run = source.slice(source.lastIndexOf('      run: |') + '      run: |'.length)
    .trimStart().split('\n').map(line => line.replace(/^        /, '')).join('\n')
  const directory = mkdtempSync(path.join(tmpdir(), 'feed-node-shadow-'))
  t.after(() => rmSync(directory, {recursive: true, force: true}))
  const trusted = path.join(directory, 'trusted-node'), marker = path.join(directory, 'calls')
  writeFileSync(trusted, '#!/bin/bash\nprintf "trusted:%s\\n" "$*" >> "$TEST_RECORD"\n')
  chmodSync(trusted, 0o755)
  writeFileSync(path.join(directory, 'node'), '#!/bin/bash\nprintf "attacker\\n" >> "$TEST_RECORD"\n')
  chmodSync(path.join(directory, 'node'), 0o755)
  const bash = process.platform === 'win32' ? 'C:/Program Files/Git/bin/bash.exe' : '/bin/bash'
  const result = spawnSync(bash, ['-c', 'set -eo pipefail\nexport PATH="$TEST_SHADOW:$PATH"\nnode() { printf "attacker-function\\n" >> "$TEST_RECORD"; }\n' + run],
    {encoding: 'utf8', timeout: 10000, env: {...process.env, FEED_NODE: trusted.replaceAll('\\', '/'),
      TEST_RECORD: marker.replaceAll('\\', '/'), TEST_SHADOW: directory.replaceAll('\\', '/'),
      CROSS_RUN_REUSE: 'false', SAME_JOB_HANDOFF: 'false', HARBORLINE_PLATFORM_REPO: '/fixture/platform'}})
  assert.equal(result.status, 0, result.stderr)
  assert.equal(readFileSync(marker, 'utf8'), 'trusted:eng/build-local-feed.mjs\n')
})
