import test from 'node:test'
import assert from 'node:assert/strict'
import {mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync} from 'node:fs'
import {tmpdir} from 'node:os'
import path from 'node:path'
import {createHash} from 'node:crypto'
import {createBundle, validateBundle, feedIdentity, materializeFeed, verifyFeed, packageMetadata} from '../platform-feed-artifact.mjs'

// Literal two-producer graph is an independent oracle. No Platform checkout or dotnet needed.
const version = '0.0.0-alpha.0.h123456789abc'
const pin = {repository: 'Harborline-Software/harborline-platform', commit: 'a'.repeat(40), producers: {
  'Harborline.A': 'Harborline.A.dll', 'Harborline.B': 'Harborline.B.dll',
}}
const props = Buffer.from(`<!-- Generated by eng/build-local-feed.mjs; .feed is gitignored. -->\n<Project>\n  <PropertyGroup>\n    <HarborlinePackedVersion>${version}</HarborlinePackedVersion>\n  </PropertyGroup>\n</Project>\n`)
const input = {pin, platformTree: 'b'.repeat(40), plan: {packedVersion: version,
  commands: [['pack', '/platform/A.csproj'], ['pack', '/platform/B.csproj']]},
  sdk: '11.0.100-rc.1.26425.128', node: 'v24.14.1', os: 'linux', arch: 'x64', imageOS: 'ubuntu24', imageVersion: '20260930.1',
  scripts: {'builder.mjs': 'c'.repeat(64)}, globalJson: 'd'.repeat(64)}
const identity = feedIdentity(input)
const hash = raw => createHash('sha256').update(raw).digest('hex')
function zip(entries) {
  return Buffer.concat(entries.map(([name, bytes]) => {
    const header = Buffer.alloc(30)
    header.writeUInt32LE(0x04034b50); header.writeUInt32LE(bytes.length, 18); header.writeUInt32LE(bytes.length, 22)
    header.writeUInt16LE(Buffer.byteLength(name), 26)
    return Buffer.concat([header, Buffer.from(name), bytes])
  }))
}
function pkg(id, dependencies = '', packageVersion = version, assembly = `${id}.dll`) {
  return {name: `${id}.${version}.nupkg`, bytes: zip([
    [`${id}.nuspec`, Buffer.from(`<package><metadata><id>${id}</id><version>${packageVersion}</version><dependencies><group targetFramework="net10.0">${dependencies}</group></dependencies></metadata></package>`)],
    [`lib/net10.0/${assembly}`, Buffer.from('fixture managed library bytes')],
  ])}
}
const files = () => [pkg('Harborline.A', `<dependency id="Harborline.B" version="${version}" />`), pkg('Harborline.B'), {name: 'packed-version.props', bytes: props}]
const bundle = () => createBundle(files(), identity, pin)
const validate = raw => validateBundle(raw, hash(raw), identity, pin)
function changeBundle(edit) { const object = JSON.parse(bundle()); edit(object); return Buffer.from(JSON.stringify(object)) }

test('complete two-producer feed roundtrip preserves exact bytes and dependency closure', () => {
  const raw = bundle(), restored = validate(raw)
  assert.deepEqual(restored, files())
  assert.equal(JSON.parse(raw).closure[0].dependencies[0].id, 'Harborline.B')
})
test('identity changes for every declared producer, graph, script, SDK and host input', () => {
  const alternatives = {
    pin: {...pin, commit: 'e'.repeat(40)}, platformTree: 'f'.repeat(40),
    plan: {...input.plan, packedVersion: '0.0.0-alpha.0.haaaaaaaaaaaa'}, sdk: '11.0.101', node: 'v24.15.0',
    arch: 'arm64', imageOS: 'ubuntu22', imageVersion: '20261001.1', scripts: {'builder.mjs': '0'.repeat(64)}, globalJson: '1'.repeat(64),
  }
  for (const [key, value] of Object.entries(alternatives)) {
    assert.throws(() => validateBundle(bundle(), hash(bundle()), feedIdentity({...input, [key]: value}), pin), /identity mismatch/, key)
  }
  for (const selectedPin of [{...pin, repository: 'Other/platform'}, {...pin, producers: {'Harborline.A': 'Other.dll'}}]) {
    assert.throws(() => validateBundle(bundle(), hash(bundle()), feedIdentity({...input, pin: selectedPin}), selectedPin), /identity mismatch/)
  }
  const graph = {...input.plan, commands: [['pack', '/platform/Changed.csproj']]}
  assert.throws(() => validateBundle(bundle(), hash(bundle()), feedIdentity({...input, plan: graph}), pin), /identity mismatch/)
  assert.throws(() => feedIdentity({...input, os: 'win32'}), /Linux runner/)
  assert.throws(() => feedIdentity({...input, imageVersion: ''}), /Linux runner/)
})
test('transport digest is independently bound and rejects tampering before parsing', () => {
  const raw = bundle()
  assert.throws(() => validateBundle(raw, '0'.repeat(64), identity, pin), /artifact digest mismatch/)
  assert.throws(() => validateBundle(Buffer.from('not json'), hash(raw), identity, pin), /artifact digest mismatch/)
  assert.throws(() => validateBundle(raw, '', identity, pin), /artifact digest mismatch/)
})
test('environment drift is a verified miss, source drift is fatal, and corruption never becomes a miss', () => {
  const raw = bundle(), differentImage = {...identity, imageVersion: '20261001.2'}
  assert.throws(() => validateBundle(raw, hash(raw), differentImage, pin), error => error.code === 'FEED_ENVIRONMENT_MISS' && /imageVersion/.test(error.message))
  assert.throws(() => validateBundle(raw, hash(raw), {...differentImage, globalJson: 'e'.repeat(64)}, pin), error => error.code !== 'FEED_ENVIRONMENT_MISS')
  const corrupt = changeBundle(object => { object.files[0].size++ })
  assert.throws(() => validateBundle(corrupt, hash(corrupt), differentImage, pin), error => error.code !== 'FEED_ENVIRONMENT_MISS' && /file digest/.test(error.message))
  assert.throws(() => validateBundle(raw, '0'.repeat(64), differentImage, pin), error => error.code !== 'FEED_ENVIRONMENT_MISS')
})
test('altered package bytes, props, size and per-file digest refuse even with a new envelope digest', () => {
  for (const edit of [
    object => { object.files[0].base64 = Buffer.from('altered').toString('base64') },
    object => { object.files[2].base64 = Buffer.from('<Project />').toString('base64') },
    object => { object.files[0].size++ }, object => { object.files[0].sha256 = '0'.repeat(64) },
  ]) assert.throws(() => validate(changeBundle(edit)), /file digest mismatch/)
})
test('missing, extra, duplicate and unsafe files refuse without destination writes', () => {
  for (const edit of [object => object.files.pop(), object => object.files.push(object.files[0]),
    object => { object.files[1] = object.files[0] }, object => { object.files[0].name = '../outside' },
    object => { object.files[0].name = 'Harborline.A\\outside' },
  ]) assert.throws(() => validate(changeBundle(edit)), /inventory mismatch|unsafe feed/)
})
test('same file count cannot hide renamed identity, wrong version, assembly or props', () => {
  for (const replacements of [
    [pkg('Harborline.A', '', '9.0.0'), pkg('Harborline.B'), {name: 'packed-version.props', bytes: props}],
    [pkg('Harborline.A', '', version, 'Other.dll'), pkg('Harborline.B'), {name: 'packed-version.props', bytes: props}],
    [pkg('Harborline.A'), pkg('Harborline.C'), {name: 'packed-version.props', bytes: props}],
    [pkg('Harborline.A'), pkg('Harborline.B'), {name: 'packed-version.props', bytes: Buffer.from('altered props')}],
  ]) assert.throws(() => createBundle(replacements, identity, pin), /version|assembly|inventory|props/)
})
test('dependency closure checks every group, ID and accepted version range', () => {
  for (const dependency of [
    `<dependency id="Harborline.Missing" version="${version}" />`,
    '<dependency id="Harborline.B" version="[9.0.0]" />', '<dependency id="Harborline.B" />',
  ]) assert.throws(() => createBundle([pkg('Harborline.A', dependency), ...files().slice(1)], identity, pin), /dependency/)
  for (const range of [version, `[${version}]`, `[${version},)`]) {
    assert.equal(verifyFeed([pkg('Harborline.A', `<dependency version="${range}" id="harborline.b" />`), ...files().slice(1)], pin, version).length, 2)
  }
  assert.throws(() => validate(changeBundle(object => { object.closure[0].dependencies = [] })), /closure mismatch/)
})
test('archive refuses path escape, duplicate nuspec, duplicate entries and truncated bytes', () => {
  const nuspec = Buffer.from(`<id>Harborline.A</id><version>${version}</version>`)
  for (const entries of [
    [['../evil', nuspec]], [['A.nuspec', nuspec], ['B.nuspec', nuspec]],
    [['A.nuspec', nuspec], ['a.nuspec', nuspec]],
  ]) assert.throws(() => packageMetadata(zip(entries)), /unsafe|duplicate|missing/)
  assert.throws(() => packageMetadata(files()[0].bytes.subarray(0, 40)), /truncated/)
})
test('inventory follows the selected pin rather than a hardcoded producer count', () => {
  const onePin = {...pin, producers: {'Harborline.A': 'Harborline.A.dll'}}
  const oneIdentity = feedIdentity({...input, pin: onePin})
  const raw = createBundle([pkg('Harborline.A'), {name: 'packed-version.props', bytes: props}], oneIdentity, onePin)
  assert.equal(validateBundle(raw, hash(raw), oneIdentity, onePin).length, 2)
})
test('fresh feed materialization preserves API outputs and unique consumer evidence', t => {
  const directory = mkdtempSync(path.join(tmpdir(), 'feed-artifact-test-'))
  t.after(() => { assert.equal(path.dirname(directory), tmpdir()); rmSync(directory, {recursive: true, force: true}) })
  mkdirSync(path.join(directory, 'bin')); writeFileSync(path.join(directory, 'bin', 'marker'), 'API build')
  writeFileSync(path.join(directory, 'receipt.json'), 'unique receipt')
  const feed = path.join(directory, '.feed')
  materializeFeed(validate(bundle()), feed)
  assert.deepEqual(readdirSync(feed).sort(), files().map(file => file.name).sort())
  assert.equal(readFileSync(path.join(directory, 'receipt.json'), 'utf8'), 'unique receipt')
  assert.equal(readFileSync(path.join(directory, 'bin', 'marker'), 'utf8'), 'API build')
  assert.throws(() => materializeFeed([{name: '../outside', bytes: props}], feed), /unsafe/)
})
