// <auto-generated />
using Harborline.Api.LocalNodeHost.Data.Search;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Search.Migrations;

[DbContext(typeof(NodeLocalSearchDbContext))]
[Migration("20260902084321_HistoricalAuthorizationEffectiveTime")]
partial class _20260902084321_HistoricalAuthorizationEffectiveTime
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Authorization.AuthorizationBindingRevisionRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("DefinitionId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("definition_id");

                b.Property<long>("Revision")
                    .HasColumnType("INTEGER")
                    .HasColumnName("revision");

                b.Property<long>("ChangedAtUnixMs")
                    .HasColumnType("INTEGER")
                    .HasColumnName("changed_at_unix_ms");

                b.Property<string>("ChangedBy")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("changed_by");

                b.Property<string>("Reason")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT")
                    .HasColumnName("reason");

                b.Property<int?>("Warning")
                    .HasColumnType("INTEGER")
                    .HasColumnName("warning");

                b.HasKey("TenantId", "DefinitionId", "Revision");

                b.ToTable("authorization_binding_revisions", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Authorization.AuthorizationBindingRoleRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("DefinitionId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("definition_id");

                b.Property<long>("Revision")
                    .HasColumnType("INTEGER")
                    .HasColumnName("revision");

                b.Property<string>("Vocabulary")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("vocabulary");

                b.Property<string>("RoleName")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("role_name");

                b.HasKey("TenantId", "DefinitionId", "Revision", "Vocabulary", "RoleName");

                b.ToTable("authorization_binding_roles", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Authorization.AuthorizationCatalogVersionRow", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<long>("Version")
                    .HasColumnType("INTEGER")
                    .HasColumnName("version");

                b.HasKey("Id");

                b.ToTable("authorization_catalog_version", (string)null);

                b.HasData(
                    new
                    {
                        Id = 1,
                        Version = 0L
                    });
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Authorization.AuthorizationClosureEntryRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("PrincipalId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("principal_id");

                b.Property<string>("Operation")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("operation");

                b.Property<int>("ScopeType")
                    .HasColumnType("INTEGER")
                    .HasColumnName("scope_type");

                b.Property<string>("ScopeValue")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT")
                    .HasColumnName("scope_value");

                b.Property<string>("RoleVocabulary")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("role_vocabulary");

                b.Property<string>("RoleName")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("role_name");

                b.Property<string>("GrantId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("grant_id");

                b.Property<string>("DefinitionId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("definition_id");

                b.Property<long>("ValidFromUnixMs")
                    .HasColumnType("INTEGER")
                    .HasColumnName("valid_from_unix_ms");

                b.Property<long?>("ValidToUnixMs")
                    .HasColumnType("INTEGER")
                    .HasColumnName("valid_to_unix_ms");

                b.HasKey("TenantId", "PrincipalId", "Operation", "ScopeType", "ScopeValue", "RoleVocabulary", "RoleName", "GrantId", "DefinitionId");

                b.HasIndex("TenantId", "Operation", "ScopeValue", "PrincipalId")
                    .HasDatabaseName("IX_authorization_principal_atom_closure_tenant_operation_scope_principal");

                b.HasIndex("TenantId", "PrincipalId", "Operation", "ScopeValue")
                    .HasDatabaseName("IX_authorization_principal_atom_closure_tenant_principal_operation_scope");

                b.HasIndex("TenantId", "RoleVocabulary", "RoleName", "Operation", "ScopeValue")
                    .HasDatabaseName("IX_authorization_principal_atom_closure_tenant_role_operation_scope");

                b.ToTable("authorization_principal_atom_closure", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Authorization.AuthorizationClosureStateRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<long>("BuiltCatalogVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("built_catalog_version");

                b.Property<long>("BuiltTenantVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("built_tenant_version");

                b.HasKey("TenantId");

                b.ToTable("authorization_closure_state", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Authorization.AuthorizationDefinitionRow", b =>
            {
                b.Property<string>("DefinitionId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("definition_id");

                b.Property<long>("Revision")
                    .HasColumnType("INTEGER")
                    .HasColumnName("revision");

                b.Property<long?>("EffectiveAtUnixMs")
                    .HasColumnType("INTEGER")
                    .HasColumnName("effective_at_unix_ms");

                b.Property<string>("Operation")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("operation");

                b.Property<string>("PublisherPackageId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("publisher_package_id");

                b.Property<int>("ScopeType")
                    .HasColumnType("INTEGER")
                    .HasColumnName("scope_type");

                b.Property<string>("ScopeValue")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("TEXT")
                    .HasColumnName("scope_value");

                b.HasKey("DefinitionId", "Revision");

                b.ToTable("authorization_capability_definitions", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Authorization.AuthorizationOfferedRoleRow", b =>
            {
                b.Property<string>("DefinitionId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("definition_id");

                b.Property<long>("Revision")
                    .HasColumnType("INTEGER")
                    .HasColumnName("revision");

                b.Property<string>("Vocabulary")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("vocabulary");

                b.Property<string>("RoleName")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("role_name");

                b.HasKey("DefinitionId", "Revision", "Vocabulary", "RoleName");

                b.ToTable("authorization_capability_offered_roles", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Authorization.AuthorizationRoleRow", b =>
            {
                b.Property<string>("Vocabulary")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("vocabulary");

                b.Property<string>("RoleName")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("role_name");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("display_name");

                b.Property<bool>("IsSealed")
                    .HasColumnType("INTEGER")
                    .HasColumnName("is_sealed");

                b.Property<string>("OwnerId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("owner_id");

                b.Property<int>("OwnerKind")
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_kind");

                b.Property<string>("RoleDefinitionId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("role_definition_id");

                b.HasKey("Vocabulary", "RoleName");

                b.ToTable("authorization_roles", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Authorization.AuthorizationTenantVersionRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<long>("Version")
                    .HasColumnType("INTEGER")
                    .HasColumnName("version");

                b.HasKey("TenantId");

                b.ToTable("authorization_tenant_versions", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.SearchEdgeRow", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<string>("EdgeType")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("edge_type");

                b.Property<string>("SourceRecordId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("source_record_id");

                b.Property<string>("TargetRecordId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("target_record_id");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.HasKey("Id");

                b.HasIndex("TenantId", "SourceRecordId");

                b.HasIndex("TenantId", "TargetRecordId");

                b.ToTable("search_edges", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.SearchNodeRow", b =>
            {
                b.Property<string>("RecordId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("record_id");

                b.Property<string>("Body")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("body");

                b.Property<string>("NodeType")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("node_type");

                b.Property<int>("Residency")
                    .HasColumnType("INTEGER")
                    .HasColumnName("residency");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("title");

                b.HasKey("RecordId");

                b.HasIndex("TenantId");

                b.HasIndex("TenantId", "NodeType");

                b.ToTable("search_nodes", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.Vector.GrantAuthorizationEpochRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("PrincipalId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("principal_id");

                b.Property<long>("AuthorizationEpoch")
                    .HasColumnType("INTEGER")
                    .HasColumnName("authorization_epoch");

                b.HasKey("TenantId", "PrincipalId");

                b.ToTable("search_grant_authorization_epochs", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.Vector.GrantRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("GrantId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("grant_id");

                b.Property<string>("Approver")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("approver");

                b.Property<long>("GrantedAtUnixMs")
                    .HasColumnType("INTEGER")
                    .HasColumnName("granted_at_unix_ms");

                b.Property<string>("GrantedBy")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("granted_by");

                b.Property<int>("GranterKind")
                    .HasColumnType("INTEGER")
                    .HasColumnName("granter_kind");

                b.Property<long>("LastReviewedAtUnixMs")
                    .HasColumnType("INTEGER")
                    .HasColumnName("last_reviewed_at_unix_ms");

                b.Property<string>("LastReviewedBy")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("last_reviewed_by");

                b.Property<long>("OwnerVersion")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(1L)
                    .HasColumnName("owner_version");

                b.Property<string>("ReasonCode")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("reason_code");

                b.Property<string>("ReasonReference")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("reason_reference");

                b.Property<int>("Residency")
                    .HasColumnType("INTEGER")
                    .HasColumnName("residency");

                b.Property<string>("RevocationReasonCode")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("revocation_reason_code");

                b.Property<string>("RevocationReasonReference")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("revocation_reason_reference");

                b.Property<long?>("RevokedAtUnixMs")
                    .HasColumnType("INTEGER")
                    .HasColumnName("revoked_at_unix_ms");

                b.Property<string>("RevokedBy")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("revoked_by");

                b.Property<string>("RoleName")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("role_name");

                b.Property<string>("RoleVocabulary")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("role_vocabulary");

                b.Property<int>("ScopeType")
                    .HasColumnType("INTEGER")
                    .HasColumnName("scope_type");

                b.Property<string>("ScopeValue")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("TEXT")
                    .HasColumnName("scope_value");

                b.Property<int>("Source")
                    .HasColumnType("INTEGER")
                    .HasColumnName("source");

                b.Property<string>("SourceReference")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("source_reference");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER")
                    .HasColumnName("status");

                b.Property<string>("SubjectId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("subject_id");

                b.Property<string>("ValidityChangeReasonCode")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("validity_change_reason_code");

                b.Property<string>("ValidityChangeReasonReference")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("validity_change_reason_reference");

                b.Property<string>("ValidityChangedBy")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("validity_changed_by");

                b.Property<long>("ValidityFromUnixMs")
                    .HasColumnType("INTEGER")
                    .HasColumnName("validity_from_unix_ms");

                b.Property<long?>("ValidityUntilUnixMs")
                    .HasColumnType("INTEGER")
                    .HasColumnName("validity_until_unix_ms");

                b.HasKey("TenantId", "GrantId");

                b.HasIndex("TenantId", "SourceReference")
                    .IsUnique();

                b.HasIndex("TenantId", "SubjectId");

                b.ToTable("search_grants", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.Vector.SubjectErasureRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("SubjectId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("subject_id");

                b.Property<long>("ErasedAtUnixMs")
                    .HasColumnType("INTEGER")
                    .HasColumnName("erased_at_unix_ms");

                b.HasKey("TenantId", "SubjectId");

                b.ToTable("search_subject_erasures", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.Vector.SubjectTombstoneRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("Pseudonym")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("pseudonym");

                b.Property<string>("ApprovingActorsJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("approving_actors_json");

                b.Property<long>("ErasedAtUnixMs")
                    .HasColumnType("INTEGER")
                    .HasColumnName("erased_at_unix_ms");

                b.Property<string>("LegalBasis")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("legal_basis");

                b.HasKey("TenantId", "Pseudonym");

                b.ToTable("search_subject_tombstones", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.Vector.VecRow", b =>
            {
                b.Property<string>("RecordId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("record_id");

                b.Property<int>("Dimension")
                    .HasColumnType("INTEGER")
                    .HasColumnName("dimension");

                b.Property<byte[]>("EmbeddingNonce")
                    .IsRequired()
                    .HasColumnType("BLOB")
                    .HasColumnName("embedding_nonce");

                b.Property<byte[]>("EncryptedEmbedding")
                    .IsRequired()
                    .HasColumnType("BLOB")
                    .HasColumnName("encrypted_embedding");

                b.Property<int>("KeyVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("key_version");

                b.Property<string>("Model")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("model");

                b.Property<string>("ModelVersion")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("model_version");

                b.Property<int>("Residency")
                    .HasColumnType("INTEGER")
                    .HasColumnName("residency");

                b.Property<string>("SubjectId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("subject_id");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.HasKey("RecordId");

                b.HasIndex("TenantId");

                b.HasIndex("TenantId", "SubjectId");

                b.ToTable("search_vec_rows", (string)null);
            });
#pragma warning restore 612, 618
    }
}
