// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Search;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Search.Migrations
{
    [DbContext(typeof(NodeLocalSearchDbContext))]
    [Migration("20260624111430_SearchInitial")]
    partial class _20260624111430_SearchInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.4.26230.115");

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.SearchEdgeRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("EdgeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("edge_type");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_record_id");

                    b.Property<string>("TargetRecordId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_record_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SourceRecordId");

                    b.HasIndex("TenantId", "TargetRecordId");

                    b.ToTable("search_edges", (string)null);
                });

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.SearchNodeRow", b =>
                {
                    b.Property<string>("RecordId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("record_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("node_type");

                    b.Property<int>("Residency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("residency");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("RecordId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "NodeType");

                    b.ToTable("search_nodes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
