// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Maintenance;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Maintenance.Migrations
{
    [DbContext(typeof(NodeLocalMaintenanceDbContext))]
    partial class NodeLocalMaintenanceDbContextModelSnapshot : ModelSnapshot
    {
        // If you encounter a merge conflict in the line below, it means you need to
        // discard one of the migration branches and recreate its migrations on top of
        // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
        public override string LastMigrationId => "20260613223256_MaintenanceInitial";

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Maintenance.MaintenanceTicketRecord", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_to");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("TEXT")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("priority");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("property");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolution");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.HasKey("Name");

                    b.HasIndex("Status");

                    b.ToTable("maintenance_tickets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
