// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.OrgBranding;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.OrgBranding.Migrations;

[DbContext(typeof(NodeLocalOrgBrandingDbContext))]
[Migration("20260707103037_OrgBrandingInitial")]
partial class _20260707103037_OrgBrandingInitial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.OrgBranding.OrgBrandingRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("AccentColor")
                    .HasMaxLength(9)
                    .HasColumnType("TEXT")
                    .HasColumnName("accent_color");

                b.Property<string>("AccentForeground")
                    .HasMaxLength(9)
                    .HasColumnType("TEXT")
                    .HasColumnName("accent_foreground");

                b.Property<string>("DisplayName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("display_name");

                b.Property<string>("LogoDarkRef")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("logo_dark_ref");

                b.Property<string>("LogoRef")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("logo_ref");

                b.Property<long>("UpdatedAt")
                    .HasColumnType("INTEGER")
                    .HasColumnName("updated_at");

                b.Property<string>("UpdatedBy")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("updated_by");

                b.HasKey("TenantId");

                b.ToTable("org_branding", (string)null);
            });
#pragma warning restore 612, 618
    }
}
