// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Identity;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Identity.Migrations;

[DbContext(typeof(NodeLocalInstallationIdentityDbContext))]
[Migration("20260713233947_InstallationIdentityCoordination")]
partial class _20260713233947_InstallationIdentityCoordination
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAccessGrantRecord", b =>
            {
                b.Property<string>("AccountId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("account_id");

                b.Property<string>("AuditCorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("audit_correlation_id");

                b.Property<long>("AuthorizationEpoch")
                    .HasColumnType("INTEGER")
                    .HasColumnName("authorization_epoch");

                b.Property<long>("CreatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("created_at_utc");

                b.Property<string>("GrantId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("grant_id");

                b.Property<string>("IssuerId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("issuer_id");

                b.Property<string>("IssuerKind")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("issuer_kind");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<string>("PermissionsJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("permissions_json");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("status");

                b.Property<long>("UpdatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("updated_at_utc");

                b.HasKey("AccountId");

                b.HasAlternateKey("GrantId")
                    .HasName("ak_installation_access_grants_grant_id");

                b.HasIndex("AuditCorrelationId")
                    .IsUnique()
                    .HasDatabaseName("ux_installation_access_grants_audit_correlation");

                b.ToTable("installation_access_grants", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAccountRecord", b =>
            {
                b.Property<string>("AccountId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("account_id");

                b.Property<long>("CreatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("created_at_utc");

                b.Property<string>("CredentialAlgorithm")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("credential_algorithm");

                b.Property<string>("CredentialCeremonyId")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("credential_ceremony_id");

                b.Property<string>("CredentialHash")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("credential_hash");

                b.Property<int>("CredentialVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("credential_version");

                b.Property<string>("NormalizedUsername")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("TEXT")
                    .HasColumnName("normalized_username");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<long>("SecurityVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("security_version");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("status");

                b.Property<long>("UpdatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("updated_at_utc");

                b.HasKey("AccountId");

                b.HasIndex("NormalizedUsername")
                    .IsUnique()
                    .HasDatabaseName("ux_installation_accounts_normalized_username");

                b.ToTable("installation_accounts", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAuditEnvelopeRecord", b =>
            {
                b.Property<string>("InstallationIdentityId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("installation_identity_id");

                b.Property<long>("Sequence")
                    .HasColumnType("INTEGER")
                    .HasColumnName("sequence");

                b.Property<string>("ActorId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("actor_id");

                b.Property<string>("ActorKind")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("actor_kind");

                b.Property<string>("CommandFingerprint")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("command_fingerprint");

                b.Property<string>("CorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("correlation_id");

                b.Property<string>("EnvelopeHash")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("envelope_hash");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("event_type");

                b.Property<long>("OccurredAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("occurred_at_utc");

                b.Property<string>("PayloadDigest")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("payload_digest");

                b.Property<string>("PreviousHash")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("previous_hash");

                b.Property<long>("RootEpoch")
                    .HasColumnType("INTEGER")
                    .HasColumnName("root_epoch");

                b.Property<string>("RootPublicKeyFingerprint")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("root_public_key_fingerprint");

                b.HasKey("InstallationIdentityId", "Sequence");

                b.HasIndex("CorrelationId")
                    .IsUnique()
                    .HasDatabaseName("ux_installation_audit_envelopes_correlation");

                b.ToTable("installation_audit_envelopes", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAuditHeadRecord", b =>
            {
                b.Property<string>("InstallationIdentityId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("installation_identity_id");

                b.Property<string>("HeadHash")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("head_hash");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<long>("Sequence")
                    .HasColumnType("INTEGER")
                    .HasColumnName("sequence");

                b.Property<long>("UpdatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("updated_at_utc");

                b.HasKey("InstallationIdentityId");

                b.ToTable("installation_audit_heads", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityCoordinatorRecord", b =>
            {
                b.Property<string>("CorrelationId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("correlation_id");

                b.Property<string>("AccountId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("account_id");

                b.Property<string>("ActorAccountId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("actor_account_id");

                b.Property<string>("AuthorityEvidenceDigest")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("authority_evidence_digest");

                b.Property<string>("CommandFingerprint")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("command_fingerprint");

                b.Property<string>("CommandType")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("command_type");

                b.Property<long>("CreatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("created_at_utc");

                b.Property<long>("ExpectedAccountOwnerVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("expected_account_owner_version");

                b.Property<long>("ExpectedAccountSecurityVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("expected_account_security_version");

                b.Property<long>("ExpectedActorOwnerVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("expected_actor_owner_version");

                b.Property<long>("ExpectedActorSecurityVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("expected_actor_security_version");

                b.Property<string>("FailureCode")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("failure_code");

                b.Property<string>("FinalReceiptsJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("final_receipts_json");

                b.Property<string>("IntentPayloadJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("intent_payload_json");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<int>("PayloadSchemaVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("payload_schema_version");

                b.Property<string>("State")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("state");

                b.Property<string>("TenantIdsJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_ids_json");

                b.Property<long>("UpdatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("updated_at_utc");

                b.HasKey("CorrelationId");

                b.HasIndex("AccountId", "State")
                    .HasDatabaseName("ix_installation_identity_coordinators_account_state");

                b.ToTable("installation_identity_coordinators", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityRecord", b =>
            {
                b.Property<string>("SingletonKey")
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("singleton_key");

                b.Property<long>("ActiveRootEpoch")
                    .HasColumnType("INTEGER")
                    .HasColumnName("active_root_epoch");

                b.Property<long>("AuthorityVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("authority_version");

                b.Property<long>("CreatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("created_at_utc");

                b.Property<string>("InstallationIdentityId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("installation_identity_id");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<long>("UpdatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("updated_at_utc");

                b.HasKey("SingletonKey");

                b.HasAlternateKey("InstallationIdentityId")
                    .HasName("ak_installation_identity_id");

                b.ToTable("installation_identity", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationRootKeyEpochRecord", b =>
            {
                b.Property<string>("InstallationIdentityId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("installation_identity_id");

                b.Property<long>("EpochNumber")
                    .HasColumnType("INTEGER")
                    .HasColumnName("epoch_number");

                b.Property<long>("CreatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("created_at_utc");

                b.Property<string>("PreviousRootFingerprint")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("previous_root_fingerprint");

                b.Property<long?>("RetiredAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("retired_at_utc");

                b.Property<string>("RootPublicKeyFingerprint")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("root_public_key_fingerprint");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("status");

                b.Property<string>("TransitionCorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("transition_correlation_id");

                b.HasKey("InstallationIdentityId", "EpochNumber");

                b.HasIndex("RootPublicKeyFingerprint")
                    .IsUnique()
                    .HasDatabaseName("ux_installation_root_key_epochs_fingerprint");

                b.HasIndex("Status")
                    .IsUnique()
                    .HasDatabaseName("ux_installation_root_key_epochs_one_active")
                    .HasFilter("status = 'Active'");

                b.HasIndex("TransitionCorrelationId")
                    .IsUnique()
                    .HasDatabaseName("ux_installation_root_key_epochs_correlation");

                b.ToTable("installation_root_key_epochs", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAccessGrantRecord", b =>
            {
                b.HasOne("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAccountRecord", null)
                    .WithOne()
                    .HasForeignKey("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAccessGrantRecord", "AccountId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAuditEnvelopeRecord", b =>
            {
                b.HasOne("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityRecord", null)
                    .WithMany()
                    .HasForeignKey("InstallationIdentityId")
                    .HasPrincipalKey("InstallationIdentityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAuditHeadRecord", b =>
            {
                b.HasOne("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityRecord", null)
                    .WithOne()
                    .HasForeignKey("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAuditHeadRecord", "InstallationIdentityId")
                    .HasPrincipalKey("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityRecord", "InstallationIdentityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityCoordinatorRecord", b =>
            {
                b.HasOne("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAccountRecord", null)
                    .WithMany()
                    .HasForeignKey("AccountId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationRootKeyEpochRecord", b =>
            {
                b.HasOne("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityRecord", null)
                    .WithMany()
                    .HasForeignKey("InstallationIdentityId")
                    .HasPrincipalKey("InstallationIdentityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
