// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Identity;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Identity.Migrations;

[DbContext(typeof(NodeLocalInstallationIdentityDbContext))]
partial class NodeLocalInstallationIdentityDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260902140000_BootstrapClaimMarker";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.BootstrapClaimMarkerRecord", b =>
            {
                b.Property<string>("SingletonKey")
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("singleton_key");

                b.Property<long>("ClaimedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("claimed_at_utc");

                b.Property<string>("GrantId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("grant_id");

                b.Property<string>("InstallationId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("installation_id");

                b.Property<string>("IssuerIdentity")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("issuer_identity");

                b.Property<string>("IssuerKind")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("issuer_kind");

                b.Property<string>("NonceDigest")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("nonce_digest");

                b.HasKey("SingletonKey");

                b.HasIndex("GrantId")
                    .IsUnique()
                    .HasDatabaseName("ux_bootstrap_claim_marker_grant");

                b.HasIndex("NonceDigest")
                    .IsUnique()
                    .HasDatabaseName("ux_bootstrap_claim_marker_nonce");

                b.ToTable("bootstrap_claim_marker", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.BootstrapClaimWindowRecord", b =>
            {
                b.Property<string>("SingletonKey")
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("singleton_key");

                b.Property<long>("DeadlineUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("deadline_utc");

                b.Property<string>("InstallationId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("installation_id");

                b.Property<long>("IssuedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("issued_at_utc");

                b.HasKey("SingletonKey");

                b.ToTable("bootstrap_claim_window", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.AccountSetupInvitationRecord", b =>
            {
                b.Property<string>("InvitationId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("invitation_id");

                b.Property<long>("AbsoluteExpiresAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("absolute_expires_at_utc");

                b.Property<string>("CommandFingerprint")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("command_fingerprint");

                b.Property<long?>("ConsumedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("consumed_at_utc");

                b.Property<string>("InviterAccountId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("inviter_account_id");

                b.Property<long>("InviterAuthorizationEpoch")
                    .HasColumnType("INTEGER")
                    .HasColumnName("inviter_authorization_epoch");

                b.Property<string>("InviterGrantId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("inviter_grant_id");

                b.Property<long>("InviterGrantOwnerVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("inviter_grant_owner_version");

                b.Property<string>("InviterMembershipId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("inviter_membership_id");

                b.Property<long>("InviterMembershipOwnerVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("inviter_membership_owner_version");

                b.Property<string>("InviterPartyId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("inviter_party_id");

                b.Property<string>("InviterPrincipalId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("inviter_principal_id");

                b.Property<string>("InviterSessionCorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("inviter_session_correlation_id");

                b.Property<long>("IssuedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("issued_at_utc");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<string>("Purpose")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("purpose");

                b.Property<string>("RequestedPermissionsJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("requested_permissions_json");

                b.Property<long?>("RevokedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("revoked_at_utc");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("TokenDigest")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("token_digest");

                b.HasKey("InvitationId");

                b.HasIndex("TokenDigest")
                    .IsUnique()
                    .HasDatabaseName("ux_account_setup_invitation_token_digest");

                b.HasIndex("TenantId", "AbsoluteExpiresAtUtc")
                    .HasDatabaseName("ix_account_setup_invitation_expiry");

                b.HasIndex("TenantId", "CommandFingerprint")
                    .IsUnique()
                    .HasDatabaseName("ux_account_setup_invitation_command");

                b.ToTable("account_setup_invitations", null, t =>
                    {
                        t.HasCheckConstraint("ck_account_setup_invitation_digest", "length(token_digest) = 64 AND token_digest NOT GLOB '*[^0-9A-F]*'");

                        t.HasCheckConstraint("ck_account_setup_invitation_expiry", "absolute_expires_at_utc > issued_at_utc");

                        t.HasCheckConstraint("ck_account_setup_invitation_owner_version", "owner_version > 0");

                        t.HasCheckConstraint("ck_account_setup_invitation_purpose", "purpose = 'AccountSetup'");
                    });
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAccessGrantRecord", b =>
            {
                b.Property<string>("AccountId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("account_id");

                b.Property<string>("AuditCorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("audit_correlation_id");

                b.Property<long>("AuthorizationEpoch")
                    .HasColumnType("INTEGER")
                    .HasColumnName("authorization_epoch");

                b.Property<long>("CreatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("created_at_utc");

                b.Property<string>("GrantId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("grant_id");

                b.Property<string>("IssuerId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("issuer_id");

                b.Property<string>("IssuerKind")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("issuer_kind");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<string>("PermissionsJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("permissions_json");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("status");

                b.Property<long>("UpdatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("updated_at_utc");

                b.HasKey("AccountId");

                b.HasAlternateKey("GrantId")
                    .HasName("ak_installation_access_grants_grant_id");

                b.HasIndex("AuditCorrelationId")
                    .IsUnique()
                    .HasDatabaseName("ux_installation_access_grants_audit_correlation");

                b.ToTable("installation_access_grants", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAccountRecord", b =>
            {
                b.Property<string>("AccountId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("account_id");

                b.Property<long>("CreatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("created_at_utc");

                b.Property<string>("CredentialAlgorithm")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("credential_algorithm");

                b.Property<string>("CredentialCeremonyId")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("credential_ceremony_id");

                b.Property<string>("CredentialHash")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("credential_hash");

                b.Property<int>("CredentialVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("credential_version");

                b.Property<string>("NormalizedUsername")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("TEXT")
                    .HasColumnName("normalized_username");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<long>("SecurityVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("security_version");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("status");

                b.Property<long>("UpdatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("updated_at_utc");

                b.HasKey("AccountId");

                b.HasIndex("NormalizedUsername")
                    .IsUnique()
                    .HasDatabaseName("ux_installation_accounts_normalized_username");

                b.ToTable("installation_accounts", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAuditEnvelopeRecord", b =>
            {
                b.Property<string>("InstallationIdentityId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("installation_identity_id");

                b.Property<long>("Sequence")
                    .HasColumnType("INTEGER")
                    .HasColumnName("sequence");

                b.Property<string>("ActorId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("actor_id");

                b.Property<string>("ActorKind")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("actor_kind");

                b.Property<string>("CommandFingerprint")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("command_fingerprint");

                b.Property<string>("CorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("correlation_id");

                b.Property<string>("EnvelopeHash")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("envelope_hash");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("event_type");

                b.Property<long>("OccurredAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("occurred_at_utc");

                b.Property<string>("PayloadDigest")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("payload_digest");

                b.Property<string>("PreviousHash")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("previous_hash");

                b.Property<long>("RootEpoch")
                    .HasColumnType("INTEGER")
                    .HasColumnName("root_epoch");

                b.Property<string>("RootPublicKeyFingerprint")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("root_public_key_fingerprint");

                b.HasKey("InstallationIdentityId", "Sequence");

                b.HasIndex("CorrelationId")
                    .IsUnique()
                    .HasDatabaseName("ux_installation_audit_envelopes_correlation");

                b.ToTable("installation_audit_envelopes", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAuditHeadRecord", b =>
            {
                b.Property<string>("InstallationIdentityId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("installation_identity_id");

                b.Property<string>("HeadHash")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("head_hash");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<long>("Sequence")
                    .HasColumnType("INTEGER")
                    .HasColumnName("sequence");

                b.Property<long>("UpdatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("updated_at_utc");

                b.HasKey("InstallationIdentityId");

                b.ToTable("installation_audit_heads", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityCoordinatorRecord", b =>
            {
                b.Property<string>("CorrelationId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("correlation_id");

                b.Property<string>("AccountId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("account_id");

                b.Property<string>("ActorAccountId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("actor_account_id");

                b.Property<string>("AuthorityEvidenceDigest")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("authority_evidence_digest");

                b.Property<string>("CommandFingerprint")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("command_fingerprint");

                b.Property<string>("CommandType")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("command_type");

                b.Property<long>("CreatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("created_at_utc");

                b.Property<long>("ExpectedAccountOwnerVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("expected_account_owner_version");

                b.Property<long>("ExpectedAccountSecurityVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("expected_account_security_version");

                b.Property<long>("ExpectedActorOwnerVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("expected_actor_owner_version");

                b.Property<long>("ExpectedActorSecurityVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("expected_actor_security_version");

                b.Property<string>("FailureCode")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("failure_code");

                b.Property<string>("FinalReceiptsJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("final_receipts_json");

                b.Property<string>("IntentPayloadJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("intent_payload_json");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<int>("PayloadSchemaVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("payload_schema_version");

                b.Property<string>("State")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("state");

                b.Property<string>("TenantIdsJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_ids_json");

                b.Property<long>("UpdatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("updated_at_utc");

                b.HasKey("CorrelationId");

                b.HasIndex("AccountId", "State")
                    .HasDatabaseName("ix_installation_identity_coordinators_account_state");

                b.ToTable("installation_identity_coordinators", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityCutoverStateRecord", b =>
            {
                b.Property<string>("SingletonKey")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("singleton_key");

                b.Property<long>("AuthorityVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("authority_version");

                b.Property<long?>("CommittedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("committed_at_utc");

                b.Property<string>("FinalVerificationDigest")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("final_verification_digest");

                b.Property<string>("LegacyBearerRevocationDigest")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("legacy_bearer_revocation_digest");

                b.Property<string>("MigrationRunId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("migration_run_id");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<string>("SourceWatermarkDigest")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("source_watermark_digest");

                b.Property<string>("Stage")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("stage");

                b.Property<long>("UpdatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("updated_at_utc");

                b.Property<long>("V1WriteBarrierVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("v1_write_barrier_version");

                b.HasKey("SingletonKey");

                b.ToTable("installation_identity_cutover_state", null, t =>
                    {
                        t.HasCheckConstraint("ck_identity_cutover_authority_version", "authority_version >= 1");

                        t.HasCheckConstraint("ck_identity_cutover_barrier_version", "v1_write_barrier_version >= 0");

                        t.HasCheckConstraint("ck_identity_cutover_owner_version", "owner_version > 0");
                    });

                b.HasData(
                    new
                    {
                        SingletonKey = "installation-identity-authority",
                        AuthorityVersion = 1L,
                        OwnerVersion = 1L,
                        Stage = "LegacyV1Authoritative",
                        UpdatedAtUtc = 0L,
                        V1WriteBarrierVersion = 0L
                    });
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityMigrationCollisionRecord", b =>
            {
                b.Property<string>("CollisionId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("collision_id");

                b.Property<string>("AuditCorrelationId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("audit_correlation_id");

                b.Property<int>("CandidateCount")
                    .HasColumnType("INTEGER")
                    .HasColumnName("candidate_count");

                b.Property<string>("CollisionKeyDigest")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("collision_key_digest");

                b.Property<long>("CreatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("created_at_utc");

                b.Property<long?>("ExpectedOwnerVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("expected_owner_version");

                b.Property<long>("ExpectedSourceVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("expected_source_version");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<string>("RecoveryActorId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("recovery_actor_id");

                b.Property<long?>("RecoveryRootEpoch")
                    .HasColumnType("INTEGER")
                    .HasColumnName("recovery_root_epoch");

                b.Property<string>("RecoveryRootPublicKeyFingerprint")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("recovery_root_public_key_fingerprint");

                b.Property<string>("RepairCommandFingerprint")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("repair_command_fingerprint");

                b.Property<string>("RepairIdempotencyKeyDigest")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("repair_idempotency_key_digest");

                b.Property<string>("RepairSourceKeyDigest")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("repair_source_key_digest");

                b.Property<string>("RepairTargetDigest")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("repair_target_digest");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("status");

                b.Property<long>("UpdatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("updated_at_utc");

                b.HasKey("CollisionId");

                b.HasIndex("CollisionKeyDigest")
                    .IsUnique()
                    .HasDatabaseName("ux_identity_migration_collision_digest");

                b.ToTable("installation_identity_migration_collisions", null, t =>
                    {
                        t.HasCheckConstraint("ck_identity_collision_candidate_count", "candidate_count > 1");

                        t.HasCheckConstraint("ck_identity_collision_owner_version", "owner_version > 0");
                    });
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityMigrationLeaseRecord", b =>
            {
                b.Property<string>("SingletonKey")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("singleton_key");

                b.Property<long>("AcquiredAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("acquired_at_utc");

                b.Property<long>("ExpiresAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("expires_at_utc");

                b.Property<string>("HolderFingerprint")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("holder_fingerprint");

                b.Property<long>("LeaseGeneration")
                    .HasColumnType("INTEGER")
                    .HasColumnName("lease_generation");

                b.Property<string>("LeaseId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("lease_id");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<long?>("ReleasedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("released_at_utc");

                b.HasKey("SingletonKey");

                b.HasIndex("LeaseId")
                    .IsUnique()
                    .HasDatabaseName("ux_identity_migration_lease_id");

                b.ToTable("installation_identity_migration_lease", null, t =>
                    {
                        t.HasCheckConstraint("ck_identity_migration_lease_expiry", "expires_at_utc > acquired_at_utc");

                        t.HasCheckConstraint("ck_identity_migration_lease_generation", "lease_generation > 0");

                        t.HasCheckConstraint("ck_identity_migration_lease_owner_version", "owner_version > 0");
                    });
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityMigrationSourceWatermarkRecord", b =>
            {
                b.Property<string>("SourceKind")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("source_kind");

                b.Property<string>("SourcePartition")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("source_partition");

                b.Property<long>("CapturedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("captured_at_utc");

                b.Property<string>("HighWatermark")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("high_watermark");

                b.Property<string>("MigrationRunId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("migration_run_id");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<string>("SnapshotDigest")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("snapshot_digest");

                b.Property<long>("SourceVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("source_version");

                b.HasKey("SourceKind", "SourcePartition");

                b.HasIndex("MigrationRunId", "SourceKind")
                    .HasDatabaseName("ix_identity_source_watermarks_run_kind");

                b.ToTable("installation_identity_migration_source_watermarks", null, t =>
                    {
                        t.HasCheckConstraint("ck_identity_source_watermark_owner_version", "owner_version > 0");

                        t.HasCheckConstraint("ck_identity_source_watermark_version", "source_version >= 0");
                    });
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityMigrationTombstoneRecord", b =>
            {
                b.Property<string>("TombstoneId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("tombstone_id");

                b.Property<string>("AuditCorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("audit_correlation_id");

                b.Property<long>("CreatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("created_at_utc");

                b.Property<string>("ProjectionDigest")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("projection_digest");

                b.Property<string>("ReasonCode")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("reason_code");

                b.Property<string>("SourceKeyDigest")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("source_key_digest");

                b.Property<string>("SourceKind")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("source_kind");

                b.Property<long>("SourceVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("source_version");

                b.HasKey("TombstoneId");

                b.HasIndex("AuditCorrelationId")
                    .IsUnique()
                    .HasDatabaseName("ux_identity_migration_tombstone_audit");

                b.HasIndex("SourceKind", "SourceKeyDigest")
                    .IsUnique()
                    .HasDatabaseName("ux_identity_migration_tombstone_source");

                b.ToTable("installation_identity_migration_tombstones", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityRecord", b =>
            {
                b.Property<string>("SingletonKey")
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("singleton_key");

                b.Property<long>("ActiveRootEpoch")
                    .HasColumnType("INTEGER")
                    .HasColumnName("active_root_epoch");

                b.Property<long>("AuthorityVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("authority_version");

                b.Property<long>("CreatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("created_at_utc");

                b.Property<string>("InstallationIdentityId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("installation_identity_id");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<long>("UpdatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("updated_at_utc");

                b.HasKey("SingletonKey");

                b.HasAlternateKey("InstallationIdentityId")
                    .HasName("ak_installation_identity_id");

                b.ToTable("installation_identity", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityRootDesignationRecord", b =>
            {
                b.Property<string>("SingletonKey")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("singleton_key");

                b.Property<string>("AccountId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("account_id");

                b.Property<string>("AuditCorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("audit_correlation_id");

                b.Property<long>("DesignatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("designated_at_utc");

                b.Property<string>("DesignationId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("designation_id");

                b.Property<long>("ExpectedSourceVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("expected_source_version");

                b.Property<string>("IdempotencyKeyDigest")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("idempotency_key_digest");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<string>("SourceCompositeKeyDigest")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("source_composite_key_digest");

                b.Property<long?>("VerifiedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("verified_at_utc");

                b.HasKey("SingletonKey");

                b.HasIndex("AccountId")
                    .IsUnique();

                b.HasIndex("AuditCorrelationId")
                    .IsUnique()
                    .HasDatabaseName("ux_identity_root_designation_audit");

                b.HasIndex("DesignationId")
                    .IsUnique()
                    .HasDatabaseName("ux_identity_root_designation_id");

                b.HasIndex("IdempotencyKeyDigest")
                    .IsUnique()
                    .HasDatabaseName("ux_identity_root_designation_idempotency");

                b.ToTable("installation_identity_root_designation", null, t =>
                    {
                        t.HasCheckConstraint("ck_identity_root_designation_owner_version", "owner_version > 0");
                    });
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationRootKeyEpochRecord", b =>
            {
                b.Property<string>("InstallationIdentityId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("installation_identity_id");

                b.Property<long>("EpochNumber")
                    .HasColumnType("INTEGER")
                    .HasColumnName("epoch_number");

                b.Property<long>("CreatedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("created_at_utc");

                b.Property<string>("PreviousRootFingerprint")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("previous_root_fingerprint");

                b.Property<long?>("RetiredAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("retired_at_utc");

                b.Property<string>("RootPublicKeyFingerprint")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("root_public_key_fingerprint");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("status");

                b.Property<string>("TransitionCorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("transition_correlation_id");

                b.HasKey("InstallationIdentityId", "EpochNumber");

                b.HasIndex("RootPublicKeyFingerprint")
                    .IsUnique()
                    .HasDatabaseName("ux_installation_root_key_epochs_fingerprint");

                b.HasIndex("Status")
                    .IsUnique()
                    .HasDatabaseName("ux_installation_root_key_epochs_one_active")
                    .HasFilter("status = 'Active'");

                b.HasIndex("TransitionCorrelationId")
                    .IsUnique()
                    .HasDatabaseName("ux_installation_root_key_epochs_correlation");

                b.ToTable("installation_root_key_epochs", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.RecoveryInvitationRecord", b =>
            {
                b.Property<string>("RecoveryInvitationId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("recovery_invitation_id");

                b.Property<long>("AbsoluteExpiresAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("absolute_expires_at_utc");

                b.Property<string>("CommandFingerprint")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("command_fingerprint");

                b.Property<long?>("CompletedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("completed_at_utc");

                b.Property<long?>("ConsumedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("consumed_at_utc");

                b.Property<string>("CredentialCommitmentDigest")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("credential_commitment_digest");

                b.Property<long>("IssuedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("issued_at_utc");

                b.Property<string>("IssuerAccountId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("issuer_account_id");

                b.Property<string>("IssuerPrincipalId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("issuer_principal_id");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<long?>("RevokedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("revoked_at_utc");

                b.Property<string>("TargetAccountId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("target_account_id");

                b.Property<string>("TargetNormalizedUsername")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("TEXT")
                    .HasColumnName("target_normalized_username");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("TokenDigest")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("token_digest");

                b.HasKey("RecoveryInvitationId");

                b.HasIndex("TokenDigest")
                    .IsUnique()
                    .HasDatabaseName("ux_recovery_invitation_token_digest");

                b.HasIndex("TargetAccountId", "AbsoluteExpiresAtUtc")
                    .HasDatabaseName("ix_recovery_invitation_target_expiry");

                b.HasIndex("TenantId", "CommandFingerprint")
                    .IsUnique()
                    .HasDatabaseName("ux_recovery_invitation_command");

                b.ToTable("recovery_invitations", null, t =>
                    {
                        t.HasCheckConstraint("ck_recovery_invitation_digest", "length(token_digest) = 64 AND token_digest NOT GLOB '*[^0-9A-F]*'");

                        t.HasCheckConstraint("ck_recovery_invitation_expiry", "absolute_expires_at_utc > issued_at_utc");

                        t.HasCheckConstraint("ck_recovery_invitation_owner_version", "owner_version > 0");
                    });
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAccessGrantRecord", b =>
            {
                b.HasOne("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAccountRecord", null)
                    .WithOne()
                    .HasForeignKey("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAccessGrantRecord", "AccountId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAuditEnvelopeRecord", b =>
            {
                b.HasOne("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityRecord", null)
                    .WithMany()
                    .HasForeignKey("InstallationIdentityId")
                    .HasPrincipalKey("InstallationIdentityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAuditHeadRecord", b =>
            {
                b.HasOne("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityRecord", null)
                    .WithOne()
                    .HasForeignKey("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAuditHeadRecord", "InstallationIdentityId")
                    .HasPrincipalKey("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityRecord", "InstallationIdentityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityCoordinatorRecord", b =>
            {
                b.HasOne("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAccountRecord", null)
                    .WithMany()
                    .HasForeignKey("AccountId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityRootDesignationRecord", b =>
            {
                b.HasOne("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAccountRecord", null)
                    .WithOne()
                    .HasForeignKey("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityRootDesignationRecord", "AccountId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.InstallationRootKeyEpochRecord", b =>
            {
                b.HasOne("Harborline.Api.LocalNodeHost.Data.Identity.InstallationIdentityRecord", null)
                    .WithMany()
                    .HasForeignKey("InstallationIdentityId")
                    .HasPrincipalKey("InstallationIdentityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.RecoveryInvitationRecord", b =>
            {
                b.HasOne("Harborline.Api.LocalNodeHost.Data.Identity.InstallationAccountRecord", null)
                    .WithMany()
                    .HasForeignKey("TargetAccountId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
