// <auto-generated />
// AUTO-GENERATED by tooling/form-factor-codegen — DO NOT EDIT BY HAND.
// Source: _shared/design/form-factor.contract.json (task #154, ADR-0017 design-system substrate tier).
// Regenerate: node tooling/form-factor-codegen/generate.mjs
// Drift-checked by: packages/ui-adapters-blazor/tests/FormFactor/FormFactorDriftTests.cs
#nullable enable

namespace Harborline.Api.UIAdapters.Blazor.FormFactor;

/// <summary>The contract's own version stamp (_shared/design/form-factor.contract.json `version`).</summary>
public static class FormFactorContractVersion
{
    public const int Value = 1;
}

/// <summary>Axis A (form factor) — width-based mode queries. Tablet is the residual (not phone, not desktop).</summary>
public static class FormFactorModeQueries
{
    public const string Phone = "(max-width: 767px)";
    public const string Desktop = "(min-width: 1280px)";
}

/// <summary>Tablet mode's floor — informational; the resolver derives tablet as the residual mode.</summary>
public static class FormFactorModeThresholds
{
    public const int TabletMinWidth = 768;
}

/// <summary>Axis A sub-signals: orientation + height-class.</summary>
public static class FormFactorSubSignalQueries
{
    public const string OrientationLandscape = "(orientation: landscape)";
    public const string HeightShort = "(max-height: 500px)";
}

/// <summary>The rail floor's height requirement (canShowRail = width AND this height).</summary>
public static class FormFactorSubSignalThresholds
{
    public const int RailMinHeight = 600;
}

/// <summary>Axis B (input capability) — measured independent of size.</summary>
public static class FormFactorCapabilityQueries
{
    public const string PointerCoarse = "(pointer: coarse)";
    public const string PointerFine = "(pointer: fine)";
    public const string AnyFine = "(any-pointer: fine)";
    public const string AnyCoarse = "(any-pointer: coarse)";
    public const string Hover = "(hover: hover)";
}

/// <summary>The affordances that ARE literal CSS media queries — watched directly via matchMedia; no further derivation needed. The boolean-combinator affordances (touchSizing, showHoverAffordance, canShowMasterDetail) are NOT here — see FormFactorResolver.</summary>
public static class FormFactorAffordanceQueries
{
    public const string CanShowRail = "(min-width: 768px) and (min-height: 600px)";
    public const string CanDockSidePanel = "((min-width: 1112px) and (orientation: landscape)) or (min-width: 1280px)";
    public const string CanSplitBuilderPanes = "(min-width: 1024px)";
    public const string CanShowFullBuilder = "(min-width: 1400px)";
    public const string NeedsContentCap = "(min-width: 1440px)";
}

public enum FormFactorMode { Phone, Tablet, Desktop }
public enum FormFactorOrientation { Portrait, Landscape }
public enum FormFactorHeightClass { Short, Tall }
public enum FormFactorPointer { Coarse, Fine }

/// <summary>
/// Raw matchMedia results the JS interop layer measures — one boolean per named query above.
/// </summary>
/// <param name="PhoneWidth">Matches FormFactorModeQueries.Phone.</param>
/// <param name="DesktopWidth">Matches FormFactorModeQueries.Desktop.</param>
/// <param name="Landscape">Matches FormFactorSubSignalQueries.OrientationLandscape.</param>
/// <param name="ShortHeight">Matches FormFactorSubSignalQueries.HeightShort.</param>
/// <param name="PointerCoarse">Matches FormFactorCapabilityQueries.PointerCoarse (the PRIMARY pointer).</param>
/// <param name="AnyCoarse">Matches FormFactorCapabilityQueries.AnyCoarse (any coarse pointer is available).</param>
/// <param name="AnyFine">Matches FormFactorCapabilityQueries.AnyFine (any fine pointer is available).</param>
/// <param name="Hover">Matches FormFactorCapabilityQueries.Hover.</param>
public readonly record struct MatchedMediaState(
    bool PhoneWidth,
    bool DesktopWidth,
    bool Landscape,
    bool ShortHeight,
    bool PointerCoarse,
    bool AnyCoarse,
    bool AnyFine,
    bool Hover);

/// <summary>
/// The resolved contract state a Blazor consumer reads. `Pointer` is the PRIMARY pointer
/// (Surface Pro tablet-mode reports Coarse here even with a mouse attached — see `TouchSizing`
/// / `ShowHoverAffordance`, which key on the ANY-pointer capabilities instead).
/// </summary>
public readonly record struct ResolvedFormFactor(
    FormFactorMode Mode,
    FormFactorOrientation Orientation,
    FormFactorHeightClass HeightClass,
    FormFactorPointer Pointer,
    bool HasFinePointer,
    bool HasCoarsePointer,
    bool Hover,
    bool TouchSizing,
    bool ShowHoverAffordance,
    bool CanShowMasterDetail);

/// <summary>
/// Pure resolver: matched media-query booleans -&gt; the contract's named mode + the
/// boolean-combinator affordances (TouchSizing / ShowHoverAffordance / CanShowMasterDetail).
/// No JS interop here — <c>FormFactorService</c> (FF10) owns the matchMedia wiring; this type is
/// the single place the contract's boolean-combinator formulas are expressed in C#, generated
/// directly from the contract text (see tooling/form-factor-codegen/lib/formula.mjs), mirroring
/// the TS resolver (packages/ui-react/src/hooks/formFactor.generated.ts).
///
/// short-landscape folds into Phone deliberately (modes.phone.orShortLandscape in the contract) —
/// every adaptation a short landscape phone needs is the phone adaptation.
/// </summary>
public static class FormFactorResolver
{
    public static ResolvedFormFactor Resolve(MatchedMediaState state)
    {
        var shortLandscape = state.Landscape && state.ShortHeight;
        var mode = state.PhoneWidth || shortLandscape
            ? FormFactorMode.Phone
            : state.DesktopWidth
                ? FormFactorMode.Desktop
                : FormFactorMode.Tablet;

        return new ResolvedFormFactor(
            Mode: mode,
            Orientation: state.Landscape ? FormFactorOrientation.Landscape : FormFactorOrientation.Portrait,
            HeightClass: state.ShortHeight ? FormFactorHeightClass.Short : FormFactorHeightClass.Tall,
            Pointer: state.PointerCoarse ? FormFactorPointer.Coarse : FormFactorPointer.Fine,
            HasFinePointer: state.AnyFine,
            HasCoarsePointer: state.AnyCoarse,
            Hover: state.Hover,
            TouchSizing: (mode == FormFactorMode.Phone) || (state.AnyCoarse) /* "phone or anyCoarse" */,
            ShowHoverAffordance: (state.Hover) || (state.AnyFine) /* "hover or anyFine" */,
            CanShowMasterDetail: !(mode == FormFactorMode.Phone) /* "not phone" */
        );
    }
}
