// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Search;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Search.Migrations
{
    [DbContext(typeof(NodeLocalSearchDbContext))]
    [Migration("20260624152259_DurableSubjectErasure")]
    partial class _20260624152259_DurableSubjectErasure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.4.26230.115");

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.SearchEdgeRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("EdgeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("edge_type");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_record_id");

                    b.Property<string>("TargetRecordId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_record_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SourceRecordId");

                    b.HasIndex("TenantId", "TargetRecordId");

                    b.ToTable("search_edges", (string)null);
                });

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.SearchNodeRow", b =>
                {
                    b.Property<string>("RecordId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("record_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("node_type");

                    b.Property<int>("Residency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("residency");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("RecordId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "NodeType");

                    b.ToTable("search_nodes", (string)null);
                });

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.Vector.GrantRow", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<string>("GrantId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("grant_id");

                    b.Property<long>("GrantedAtUnixMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("granted_at_unix_ms");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("granted_by");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("principal_id");

                    b.Property<int>("Residency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("residency");

                    b.Property<long?>("RevokedAtUnixMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revoked_at_unix_ms");

                    b.Property<string>("RolesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("roles_json");

                    b.Property<string>("ScopeJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_json");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_reference");

                    b.Property<long>("ValidityFromUnixMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("validity_from_unix_ms");

                    b.Property<long?>("ValidityUntilUnixMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("validity_until_unix_ms");

                    b.HasKey("TenantId", "GrantId");

                    b.HasIndex("TenantId", "PrincipalId");

                    b.HasIndex("TenantId", "SourceReference");

                    b.ToTable("search_grants", (string)null);
                });

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.Vector.SubjectErasureRow", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_id");

                    b.Property<long>("ErasedAtUnixMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("erased_at_unix_ms");

                    b.HasKey("TenantId", "SubjectId");

                    b.ToTable("search_subject_erasures", (string)null);
                });

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.Vector.SubjectTombstoneRow", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Pseudonym")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("pseudonym");

                    b.Property<string>("ApprovingActorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("approving_actors_json");

                    b.Property<long>("ErasedAtUnixMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("erased_at_unix_ms");

                    b.Property<string>("LegalBasis")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("legal_basis");

                    b.HasKey("TenantId", "Pseudonym");

                    b.ToTable("search_subject_tombstones", (string)null);
                });

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Search.Vector.VecRow", b =>
                {
                    b.Property<string>("RecordId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("record_id");

                    b.Property<int>("Dimension")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dimension");

                    b.Property<byte[]>("EmbeddingNonce")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("embedding_nonce");

                    b.Property<byte[]>("EncryptedEmbedding")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("encrypted_embedding");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("key_version");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_version");

                    b.Property<int>("Residency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("residency");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.HasKey("RecordId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "SubjectId");

                    b.ToTable("search_vec_rows", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
