// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Properties;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Properties.Migrations
{
    [DbContext(typeof(NodeLocalPropertyDbContext))]
    partial class NodeLocalPropertyDbContextModelSnapshot : ModelSnapshot
    {
        // If you encounter a merge conflict in the line below, it means you need to
        // discard one of the migration branches and recreate its migrations on top of
        // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
        public override string LastMigrationId => "20260614220931_PropertyInitial";

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Properties.PropertyRecord", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("address_line_1");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("company");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("postal_code");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("property_name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("Units")
                        .HasColumnType("INTEGER")
                        .HasColumnName("units");

                    b.HasKey("Name");

                    b.HasIndex("Company");

                    b.HasIndex("Status");

                    b.ToTable("properties", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
