// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Calendar;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Calendar.Migrations;

[DbContext(typeof(NodeLocalCalendarDbContext))]
[Migration("20260707100739_CalendarCollectionInitial")]
partial class _20260707100739_CalendarCollectionInitial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Calendar.NodeCalendarEventRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("Id")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<string>("SnapshotJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("snapshot_json");

                b.HasKey("TenantId", "Id");

                b.HasIndex("TenantId");

                b.ToTable("calendar_events", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Calendar.NodeCalendarRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("Id")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<string>("SnapshotJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("snapshot_json");

                b.HasKey("TenantId", "Id");

                b.HasIndex("TenantId");

                b.ToTable("calendars", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Calendar.NodeResourceAvailabilityRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<int>("ResourceKind")
                    .HasColumnType("INTEGER")
                    .HasColumnName("resource_kind");

                b.Property<string>("ResourceValue")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("resource_value");

                b.Property<string>("SnapshotJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("snapshot_json");

                b.HasKey("TenantId", "ResourceKind", "ResourceValue");

                b.HasIndex("TenantId");

                b.ToTable("resource_availability", (string)null);
            });
#pragma warning restore 612, 618
    }
}
