// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Banking;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Banking.Migrations
{
    [DbContext(typeof(NodeLocalBankFeedDbContext))]
    [Migration("20260616000000_BankFeedConnectionsInitial")]
    partial class _20260616000000_BankFeedConnectionsInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.4.26230.115");

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Banking.BankFeedConnectionRecord", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("connected_at");

                    b.HasKey("AccountId");

                    b.ToTable("bank_feed_connections", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
