// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Banking;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Banking.Migrations
{
    [DbContext(typeof(NodeLocalBankFeedDbContext))]
    partial class NodeLocalBankFeedDbContextModelSnapshot : ModelSnapshot
    {
        // If you encounter a merge conflict in the line below, it means you need to
        // discard one of the migration branches and recreate its migrations on top of
        // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
        public override string LastMigrationId => "20260616000000_BankFeedConnectionsInitial";

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Banking.BankFeedConnectionRecord", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("connected_at");

                    b.HasKey("AccountId");

                    b.ToTable("bank_feed_connections", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
