using System.Text.Json;

var root = Path.GetFullPath(args.Single());
SelfTests.Run();
var tests = Path.Combine(root, "apps/local-node-host/tests");
var files = Directory.EnumerateFiles(tests, "*.cs", SearchOption.AllDirectories)
    .Where(p => !p.Split(Path.DirectorySeparatorChar).Any(part => part is "bin" or "obj"))
    .ToDictionary(p => Path.GetRelativePath(root, p).Replace('\\', '/'), File.ReadAllText);
var sites = IsolationGuard.Scan(files);
var inventoryPath = Path.Combine(root, "eng/test-isolation/legacy-debt.json");
// The legacy inventory is reviewed source debt, never regenerated by this check.
var debt = JsonSerializer.Deserialize<Dictionary<string, int>>(File.ReadAllText(inventoryPath))!;
if (debt.Any(p => p.Value <= 0)) throw new InvalidOperationException("Legacy debt counts must be positive.");
var errors = IsolationGuard.Check(sites, debt);
foreach (var error in errors) Console.Error.WriteLine(error);
Console.WriteLine($"Host test isolation: {sites.Length} mutation sites, {debt.Values.Sum()} legacy unisolated sites; {errors.Length} differences.");
return errors.Length == 0 ? 0 : 1;
