using System.Text.Json;

var root = Path.GetFullPath(args.Single());
SelfTests.Run();
var tests = Path.Combine(root, "apps/local-node-host/tests");
var files = Directory.EnumerateFiles(tests, "*.cs", SearchOption.AllDirectories)
    .Where(p => !p.Split(Path.DirectorySeparatorChar).Any(part => part is "bin" or "obj"))
    .ToDictionary(p => Path.GetRelativePath(root, p).Replace('\\', '/'), File.ReadAllText);
var sites = IsolationGuard.Scan(files);
var inventoryPath = Path.Combine(root, "eng/test-isolation/legacy-debt.json");
// The legacy inventory is reviewed source debt, never regenerated by this check.
var debt = JsonSerializer.Deserialize<Dictionary<string, IsolationGuard.LegacyDebt>>(File.ReadAllText(inventoryPath))!;
if (debt.Any(p => p.Value.Count <= 0 || p.Value.TypeSha256.Length != 64 || p.Value.Owner != "T-1031"
    || string.IsNullOrWhiteSpace(p.Value.Reason))) throw new InvalidOperationException("Legacy debt needs positive count, type hash, existing owner and reason.");
var errors = IsolationGuard.Check(sites, debt.ToDictionary(p => p.Key, p => p.Value.Count))
    .Concat(IsolationGuard.CheckHashes(sites, debt)).ToArray();
foreach (var error in errors) Console.Error.WriteLine(error);
Console.WriteLine($"Host test isolation: {sites.Length} mutation sites, {debt.Values.Sum(v => v.Count)} legacy unisolated sites; {errors.Length} differences.");
return errors.Length == 0 ? 0 : 1;
