// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Migrations;

[DbContext(typeof(LocalNodeDbContext))]
[Migration("20260730104243_AddReconciliationVersion")]
partial class _20260730104243_AddReconciliationVersion
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Harborline.Api.Blocks.Banking.Models.BankAccount", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("ArchivedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(8)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CutoverAsOf")
                    .HasColumnType("TEXT");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("EntityId")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("InstitutionName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("Kind")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("LinkedLedgerAccount")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("linked_ledger_account_json");

                b.Property<decimal>("OpeningBalance")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_bank_accounts_tenant_id");

                b.HasIndex("TenantId", "EntityId")
                    .HasDatabaseName("ix_bank_accounts_tenant_entity");

                b.ToTable("bank_accounts", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.Banking.Models.MatchLink", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("AcceptedAt")
                    .HasColumnType("TEXT");

                b.Property<decimal>("Amount")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<string>("LedgerTransaction")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("JournalEntryId");

                b.Property<string>("State")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("StatementLine")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_match_links_tenant_id");

                b.HasIndex("TenantId", "StatementLine")
                    .HasDatabaseName("ix_match_links_tenant_statement_line");

                b.ToTable("match_links", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.Banking.Models.Reconciliation", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("AccountId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<decimal>("ClearedMovement")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("LockState")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("LockedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("LockedByPrincipalId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<decimal>("OpeningBalance")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<string>("PeriodId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<decimal>("StatementClosingBalance")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("TenantId", "AccountId")
                    .HasDatabaseName("ix_reconciliations_tenant_account");

                b.HasIndex("TenantId", "AccountId", "PeriodId")
                    .IsUnique()
                    .HasDatabaseName("ux_reconciliations_tenant_account_period");

                b.ToTable("reconciliations", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.Banking.Models.StatementLine", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("AccountId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<decimal>("Amount")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(8)
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(1024)
                    .HasColumnType("TEXT");

                b.Property<bool>("Pending")
                    .HasColumnType("INTEGER");

                b.Property<DateTimeOffset>("PostedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("ProviderTxnId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("RawProviderBlob")
                    .HasMaxLength(65535)
                    .HasColumnType("TEXT")
                    .HasColumnName("raw_provider_blob");

                b.Property<string>("Source")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("source_json");

                b.Property<string>("State")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("TenantId", "AccountId")
                    .HasDatabaseName("ix_statement_lines_tenant_account");

                b.HasIndex("TenantId", "AccountId", "ProviderTxnId")
                    .HasDatabaseName("ix_statement_lines_tenant_account_provider_txn");

                b.ToTable("statement_lines", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.Docs.Models.Attachment", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ContentHash")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("DeletedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedBy")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedReason")
                    .HasMaxLength(1024)
                    .HasColumnType("TEXT");

                b.Property<string>("MimeType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("OriginalFilename")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("ReplacedByAttachmentId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ReplacesAttachmentId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("RevisionVector")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("revision_vector_json");

                b.Property<string>("Sensitivity")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<long>("SizeBytes")
                    .HasColumnType("INTEGER");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("StorageRef")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("storage_ref_json");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("ThumbnailRef")
                    .HasColumnType("TEXT")
                    .HasColumnName("thumbnail_ref_json");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<long>("Version")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_attachments_tenant_id");

                b.HasIndex("TenantId", "ContentHash")
                    .HasDatabaseName("ix_attachments_tenant_content_hash");

                b.HasIndex("TenantId", "Status")
                    .HasDatabaseName("ix_attachments_tenant_status");

                b.ToTable("attachments", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.Docs.Models.DocumentRef", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("AttachmentId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("AttachmentRole")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ClusterCode")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("DeletedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedBy")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedReason")
                    .HasMaxLength(1024)
                    .HasColumnType("TEXT");

                b.Property<string>("ParentEntityId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("ParentEntityType")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("RevisionVector")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("revision_vector_json");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<long>("Version")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("TenantId", "AttachmentId")
                    .HasDatabaseName("ix_document_refs_tenant_attachment_active");

                b.HasIndex("TenantId", "ClusterCode", "ParentEntityType", "ParentEntityId")
                    .HasDatabaseName("ix_document_refs_tenant_parent_active");

                b.ToTable("document_refs", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.FinancialAp.Models.Bill", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<decimal>("AmountPaid")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<string>("ApAccountId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("ApprovedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("ApprovedByUserId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<decimal>("Balance")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("BillDate")
                    .HasColumnType("TEXT");

                b.Property<string>("BillNumber")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ChartId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Currency")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(8)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("USD");

                b.Property<DateTimeOffset?>("DeletedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedReason")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("DueDate")
                    .HasColumnType("TEXT");

                b.Property<string>("ExternalRef")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("ExternalRefVersion")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("JournalEntryId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Lines")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("lines_json");

                b.Property<string>("Notes")
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<string>("PropertyId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("ReceivedDate")
                    .HasColumnType("TEXT");

                b.Property<string>("RevisionVector")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("revision_vector_json");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("SubLedgerAccountId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<decimal>("Subtotal")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<decimal>("TaxTotal")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("TermsId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<decimal>("Total")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("VendorId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<long>("Version")
                    .HasColumnType("INTEGER");

                b.Property<string>("VoidedByEntryId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_bills_tenant_id");

                b.HasIndex("TenantId", "ChartId")
                    .HasDatabaseName("ix_bills_tenant_chart");

                b.HasIndex("TenantId", "ChartId", "ExternalRef")
                    .HasDatabaseName("ix_bills_tenant_chart_external_ref");

                b.HasIndex("TenantId", "ChartId", "VendorId")
                    .HasDatabaseName("ix_bills_tenant_chart_vendor");

                b.HasIndex("TenantId", "ChartId", "VendorId", "BillNumber")
                    .IsUnique()
                    .HasDatabaseName("ux_bills_tenant_chart_vendor_number");

                b.ToTable("bills", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.FinancialAr.Models.Invoice", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<decimal>("AmountPaid")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<string>("ArAccountId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<decimal>("Balance")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<string>("ChartId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Currency")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(8)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("USD");

                b.Property<string>("CustomerId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("DeletedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedReason")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("DueDate")
                    .HasColumnType("TEXT");

                b.Property<string>("ExternalRef")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("InvoiceNumber")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("IssueDate")
                    .HasColumnType("TEXT");

                b.Property<string>("JournalEntryId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Lines")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("lines_json");

                b.Property<string>("Notes")
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<string>("PropertyId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("RevisionVector")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("revision_vector_json");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("SubLedgerAccountId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<decimal>("Subtotal")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<decimal>("TaxTotal")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("TermsId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<decimal>("Total")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<long>("Version")
                    .HasColumnType("INTEGER");

                b.Property<string>("VoidedByEntryId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("WrittenOffByEntryId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_invoices_tenant_id");

                b.HasIndex("TenantId", "ChartId")
                    .HasDatabaseName("ix_invoices_tenant_chart");

                b.HasIndex("TenantId", "ChartId", "CustomerId")
                    .HasDatabaseName("ix_invoices_tenant_chart_customer");

                b.HasIndex("TenantId", "ChartId", "ExternalRef")
                    .HasDatabaseName("ix_invoices_tenant_chart_external_ref");

                b.HasIndex("TenantId", "ChartId", "InvoiceNumber")
                    .IsUnique()
                    .HasDatabaseName("ux_invoices_tenant_chart_number");

                b.ToTable("invoices", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.FinancialAr.Models.RecurringInvoiceSchedule", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ArAccountId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ChartId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("CustomerId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateOnly?>("EndsOn")
                    .HasColumnType("TEXT");

                b.Property<int>("GenerateLeadDays")
                    .HasColumnType("INTEGER");

                b.Property<string>("GeneratedInvoices")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("generated_invoices_json");

                b.Property<DateTimeOffset?>("LastGeneratedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("LineTemplates")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("line_templates_json");

                b.Property<int>("LookaheadHorizonDays")
                    .HasColumnType("INTEGER");

                b.Property<string>("RecurrenceRule")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("StartsOn")
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("Timezone")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_recurring_invoice_schedules_tenant_id");

                b.HasIndex("TenantId", "Status")
                    .HasDatabaseName("ix_recurring_invoice_schedules_tenant_status");

                b.ToTable("recurring_invoice_schedules", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.FinancialLedger.Models.ChartOfAccounts", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("BaseCurrency")
                    .IsRequired()
                    .HasMaxLength(8)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<int>("FiscalYearStartDay")
                    .HasColumnType("INTEGER");

                b.Property<int>("FiscalYearStartMonth")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(true);

                b.Property<string>("LegalEntityId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("RetainedEarningsAccountId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("LegalEntityId")
                    .HasDatabaseName("ix_charts_of_accounts_entity_id");

                b.ToTable("charts_of_accounts", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.FinancialLedger.Models.GLAccount", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ChartId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("Currency")
                    .HasMaxLength(8)
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .HasMaxLength(1024)
                    .HasColumnType("TEXT");

                b.Property<string>("ExternalRef")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(true);

                b.Property<bool>("IsPostable")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(true);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("NormalBalance")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<string>("ParentAccountId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Subtype")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("TaxLineMappingId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ChartId")
                    .HasDatabaseName("ix_gl_accounts_chart_id");

                b.HasIndex("ChartId", "Code")
                    .IsUnique()
                    .HasDatabaseName("ux_gl_accounts_chart_code");

                b.ToTable("gl_accounts", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.FinancialLedger.Models.JournalEntry", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ChartId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("EntryDate")
                    .HasColumnType("TEXT");

                b.Property<string>("ExternalRef")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("Lines")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("lines_json");

                b.Property<string>("Memo")
                    .IsRequired()
                    .HasMaxLength(1024)
                    .HasColumnType("TEXT");

                b.Property<string>("PeriodId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("PostedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("ReversalOf")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ReversedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("SourceKind")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("SourceReference")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_journal_entries_tenant_id");

                b.HasIndex("TenantId", "ChartId")
                    .HasDatabaseName("ix_journal_entries_tenant_chart");

                b.HasIndex("TenantId", "SourceReference")
                    .IsUnique()
                    .HasDatabaseName("ux_journal_entries_tenant_source_ref");

                b.ToTable("journal_entries", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.FinancialLedger.Models.LegalEntity", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("CommonControlGroupId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("Kind")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("LegalName")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("TaxClassification")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_legal_entities_tenant_id");

                b.ToTable("legal_entities", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.FinancialLedger.Models.LegalEntityOwnership", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("OwnedEntityId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<decimal>("OwnershipPercent")
                    .HasPrecision(7, 4)
                    .HasColumnType("TEXT");

                b.Property<string>("ParentEntityId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_legal_entity_ownerships_tenant_id");

                b.HasIndex("TenantId", "ParentEntityId", "OwnedEntityId")
                    .IsUnique()
                    .HasDatabaseName("ux_legal_entity_ownerships_edge");

                b.ToTable("legal_entity_ownerships", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.FinancialPayments.Models.Payment", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<decimal>("Amount")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<string>("Applications")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("applications_json");

                b.Property<string>("BankAccountId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("BouncedByEntryId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ChartId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Currency")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(8)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("USD");

                b.Property<string>("Direction")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<string>("ExternalRef")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("ExternalRefVersion")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("IntendedTargetId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("IntendedTargetType")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<string>("JournalEntryId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Method")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("Notes")
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<string>("PartyId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("PaymentDate")
                    .HasColumnType("TEXT");

                b.Property<string>("PaymentNumber")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Reference")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("SourceReference")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<decimal>("UnappliedAmount")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<long>("Version")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_payments_tenant_id");

                b.HasIndex("TenantId", "SourceReference")
                    .IsUnique()
                    .HasDatabaseName("ux_payments_tenant_source_ref");

                b.HasIndex("TenantId", "ChartId", "ExternalRef")
                    .HasDatabaseName("ix_payments_tenant_chart_external_ref");

                b.HasIndex("TenantId", "ChartId", "PartyId")
                    .HasDatabaseName("ix_payments_tenant_chart_party");

                b.HasIndex("TenantId", "ChartId", "PaymentDate")
                    .HasDatabaseName("ix_payments_tenant_chart_date");

                b.HasIndex("TenantId", "ChartId", "PaymentNumber")
                    .IsUnique()
                    .HasDatabaseName("ux_payments_tenant_chart_number");

                b.HasIndex("TenantId", "IntendedTargetType", "IntendedTargetId")
                    .HasDatabaseName("ix_payments_tenant_intended_target");

                b.ToTable("payments", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.FinancialPayments.Models.PaymentApplication", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<decimal>("AmountApplied")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("AppliedDate")
                    .HasColumnType("TEXT");

                b.Property<string>("AppliedTo")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<decimal>("DiscountAmount")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.Property<string>("PaymentId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("ReversedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("ReversedByApplicationId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ReversesApplicationId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("TargetId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<decimal>("WriteoffAmount")
                    .HasPrecision(18, 4)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("TenantId", "PaymentId")
                    .HasDatabaseName("ix_payment_applications_tenant_payment");

                b.HasIndex("TenantId", "ReversesApplicationId")
                    .IsUnique()
                    .HasDatabaseName("ux_payment_applications_tenant_reverses");

                b.HasIndex("TenantId", "TargetId")
                    .HasDatabaseName("ix_payment_applications_tenant_target");

                b.ToTable("payment_applications", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.FinancialPeriods.Models.FiscalPeriod", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ChartId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ClosingJournalEntryId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("EndDate")
                    .HasColumnType("TEXT");

                b.Property<string>("FiscalYearId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Kind")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("Label")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("LockedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("SoftClosedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("StartDate")
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<int>("Version")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("FiscalYearId")
                    .HasDatabaseName("ix_fiscal_periods_fiscal_year_id");

                b.HasIndex("ChartId", "StartDate", "EndDate")
                    .HasDatabaseName("ix_fiscal_periods_chart_dates");

                b.ToTable("fiscal_periods", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.FinancialPeriods.Models.FiscalYear", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ChartId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("ClosedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("ClosingJournalEntryId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("EndDate")
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("ExternalModifiedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("ExternalRef")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("Label")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("StartDate")
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<int>("Version")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("ChartId")
                    .HasDatabaseName("ix_fiscal_years_chart_id");

                b.HasIndex("ExternalRef")
                    .HasDatabaseName("ix_fiscal_years_external_ref");

                b.ToTable("fiscal_years", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.People.Foundation.Models.EmailAddress", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Address")
                    .IsRequired()
                    .HasMaxLength(254)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("DeletedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedReason")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsPrimary")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsValidated")
                    .HasColumnType("INTEGER");

                b.Property<string>("Label")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("OptedOutAt")
                    .HasColumnType("TEXT");

                b.Property<string>("PartyId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("ReplacedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("RevisionVector")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("revision_vector_json");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("ValidatedAt")
                    .HasColumnType("TEXT");

                b.Property<long>("Version")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("TenantId", "Address")
                    .HasDatabaseName("ix_party_emails_tenant_address_active");

                b.HasIndex("TenantId", "PartyId")
                    .HasDatabaseName("ix_party_emails_tenant_party");

                b.ToTable("party_email_addresses", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.People.Foundation.Models.Party", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateOnly?>("DateOfBirth")
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("DeletedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedReason")
                    .HasMaxLength(1024)
                    .HasColumnType("TEXT");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<bool>("DoNotCall")
                    .HasColumnType("INTEGER");

                b.Property<bool>("DoNotContact")
                    .HasColumnType("INTEGER");

                b.Property<bool>("DoNotEmail")
                    .HasColumnType("INTEGER");

                b.Property<bool>("DoNotSms")
                    .HasColumnType("INTEGER");

                b.Property<string>("FamilyName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("GivenName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("Kind")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("LegalEntityType")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("LegalName")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("MiddleName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("Notes")
                    .HasMaxLength(4096)
                    .HasColumnType("TEXT");

                b.Property<string>("ParentOrgId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("PreferredLanguage")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<string>("PreferredName")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("Pronouns")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("RevisionVector")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("revision_vector_json");

                b.Property<string>("Suffix")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("Tags")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("tags_json");

                b.Property<string>("TaxId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<long>("Version")
                    .HasColumnType("INTEGER");

                b.Property<string>("WebSite")
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_parties_tenant_id");

                b.HasIndex("TenantId", "DisplayName")
                    .HasDatabaseName("ix_parties_tenant_display_name");

                b.HasIndex("TenantId", "Kind")
                    .HasDatabaseName("ix_parties_tenant_kind");

                b.ToTable("parties", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.People.Foundation.Models.PartyAddress", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("address_json");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("DeletedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedReason")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsPrimary")
                    .HasColumnType("INTEGER");

                b.Property<string>("Label")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("PartyId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("ReplacedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("RevisionVector")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("revision_vector_json");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("ValidFrom")
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("ValidTo")
                    .HasColumnType("TEXT");

                b.Property<long>("Version")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("TenantId", "PartyId")
                    .HasDatabaseName("ix_party_addresses_tenant_party");

                b.ToTable("party_addresses", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.People.Foundation.Models.PartyRole", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("DeletedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedReason")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("EndedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("EndedReason")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("PartyId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("RevisionVector")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("revision_vector_json");

                b.Property<string>("RoleName")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("RoleRecordId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("StartedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<long>("Version")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("TenantId", "PartyId")
                    .HasDatabaseName("ix_party_roles_tenant_party");

                b.HasIndex("TenantId", "PartyId", "RoleName")
                    .HasDatabaseName("ix_party_roles_tenant_party_role_active");

                b.HasIndex("TenantId", "PartyId", "RoleName", "RoleRecordId")
                    .HasDatabaseName("ux_party_roles_idempotency_active");

                b.ToTable("party_roles", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.People.Foundation.Models.PhoneNumber", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("DeletedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("DeletedReason")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("E164")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<string>("Extension")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsMobile")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsPrimary")
                    .HasColumnType("INTEGER");

                b.Property<string>("Label")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("PartyId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset?>("ReplacedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("RevisionVector")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("revision_vector_json");

                b.Property<DateTimeOffset?>("SmsOptedOutAt")
                    .HasColumnType("TEXT");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<long>("Version")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("TenantId", "E164")
                    .HasDatabaseName("ix_party_phones_tenant_e164_active");

                b.HasIndex("TenantId", "PartyId")
                    .HasDatabaseName("ix_party_phones_tenant_party");

                b.ToTable("party_phone_numbers", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.Workflow.Durable.WorkflowEventRecord", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("DataJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("data_json");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("InstanceId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("OccurredAt")
                    .IsRequired()
                    .HasMaxLength(33)
                    .HasColumnType("TEXT");

                b.Property<long>("Seq")
                    .HasColumnType("INTEGER");

                b.Property<string>("Step")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("InstanceId", "Seq")
                    .IsUnique()
                    .HasDatabaseName("ux_workflow_events_instance_seq");

                b.ToTable("workflow_events", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.Workflow.Durable.WorkflowInstanceRecord", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasMaxLength(33)
                    .HasColumnType("TEXT");

                b.Property<string>("CurrentStep")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("DefinitionKey")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("DefinitionVersion")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<int>("Iteration")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(0);

                b.Property<string>("StateJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("state_json");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedAt")
                    .IsRequired()
                    .HasMaxLength(33)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_workflow_instances_tenant_id");

                b.HasIndex("TenantId", "Status")
                    .HasDatabaseName("ix_workflow_instances_tenant_status");

                b.ToTable("workflow_instances", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.Blocks.Workflow.Durable.WorkflowStepIdempotencyRecord", b =>
            {
                b.Property<string>("Key")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<string>("CompletedAt")
                    .IsRequired()
                    .HasMaxLength(33)
                    .HasColumnType("TEXT");

                b.Property<string>("InstanceId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<int>("Iteration")
                    .HasColumnType("INTEGER");

                b.Property<string>("ResultJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("result_json");

                b.Property<string>("Step")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("Key");

                b.HasIndex("InstanceId")
                    .HasDatabaseName("ix_workflow_step_idempotency_instance");

                b.ToTable("workflow_step_idempotency", (string)null);
            });

        modelBuilder.Entity("Harborline.Bridge.Data.Financial.TenantChartMappingRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("LegalEntityId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("ChartId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.HasKey("TenantId", "LegalEntityId");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_tenant_chart_mappings_tenant_id");

                b.ToTable("tenant_chart_mappings", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Audit.NodeAuditEventRow", b =>
            {
                b.Property<string>("AuditId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("Actor")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("CorrelationId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("Hash")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<string>("OccurredAt")
                    .IsRequired()
                    .HasMaxLength(33)
                    .HasColumnType("TEXT");

                b.Property<string>("Payload")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("payload_json");

                b.Property<string>("PrevHash")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.Property<byte[]>("Signature")
                    .HasColumnType("BLOB")
                    .HasColumnName("signature");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("AuditId");

                b.HasIndex("TenantId")
                    .HasDatabaseName("ix_node_audit_events_tenant_id");

                b.HasIndex("TenantId", "CorrelationId")
                    .HasDatabaseName("ix_node_audit_events_tenant_correlation");

                b.HasIndex("TenantId", "EventType")
                    .HasDatabaseName("ix_node_audit_events_tenant_event_type");

                b.HasIndex("TenantId", "OccurredAt")
                    .HasDatabaseName("ix_node_audit_events_tenant_occurred");

                b.ToTable("node_audit_events", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Audit.NodeAuditSignatureEpochRow", b =>
            {
                b.Property<long>("EpochId")
                    .HasColumnType("INTEGER");

                b.Property<string>("BoundaryAt")
                    .IsRequired()
                    .HasMaxLength(33)
                    .HasColumnType("TEXT");

                b.Property<string>("IssuerId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<byte[]>("SealedPublicKey")
                    .IsRequired()
                    .HasColumnType("BLOB")
                    .HasColumnName("sealed_public_key");

                b.HasKey("EpochId");

                b.HasIndex("BoundaryAt")
                    .HasDatabaseName("ix_node_audit_signature_epochs_boundary");

                b.HasIndex("IssuerId")
                    .HasDatabaseName("ix_node_audit_signature_epochs_issuer");

                b.ToTable("node_audit_signature_epochs", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.HomeEpoch.HomeEpochRecord", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<long>("EpochNumber")
                    .HasColumnType("INTEGER");

                b.Property<string>("CoApproverIssuerId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("CoApproverSignature")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("HomeDeviceId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("IssuedAt")
                    .IsRequired()
                    .HasMaxLength(33)
                    .HasColumnType("TEXT");

                b.Property<string>("IssuerId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<Guid>("Nonce")
                    .HasColumnType("TEXT");

                b.Property<long>("PreviousEpochNumber")
                    .HasColumnType("INTEGER");

                b.Property<string>("PromotionKind")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT");

                b.Property<string>("Signature")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.HasKey("TenantId", "EpochNumber");

                b.HasIndex("TenantId", "EpochNumber")
                    .HasDatabaseName("ix_home_epochs_tenant_epoch");

                b.ToTable("home_epochs", (string)null);
            });
#pragma warning restore 612, 618
    }
}
