// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Roster;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Roster.Migrations
{
    [DbContext(typeof(NodeLocalRosterDbContext))]
    [Migration("20260621115445_RosterAddTransportPublicKey")]
    partial class _20260621115445_RosterAddTransportPublicKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.4.26230.115");

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Roster.NodeRosterRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AdmittedByPartyId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("admitted_by_party");

                    b.Property<string>("AdmittedByPublicKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("admitted_by_key");

                    b.Property<bool>("IsGenesis")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_genesis");

                    b.Property<long>("IssuedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("issued_at");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("NonceGuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("nonce");

                    b.Property<string>("PartyId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("party_id");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("permissions");

                    b.Property<string>("PublicKeyB64Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("public_key");

                    b.Property<string>("SignatureB64Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("signature");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("team_id");

                    b.Property<string>("TransportPublicKeyB64Url")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("transport_public_key");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId", "IssuedAtUtc");

                    b.ToTable("roster_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
