// <auto-generated />
using Harborline.Api.LocalNodeHost.Data.Roster;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Roster.Migrations;

[DbContext(typeof(NodeLocalRosterDbContext))]
partial class NodeLocalRosterDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260831184210_RosterAddAdministratorAuthority";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.CompromisedDeviceResponse.CompromisedDeviceResponseRow", b =>
            {
                b.Property<string>("CorrelationId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("correlation_id");

                b.Property<string>("PayloadJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("payload_json");

                b.Property<byte[]>("Signature")
                    .IsRequired()
                    .HasColumnType("BLOB")
                    .HasColumnName("signature");

                b.Property<long>("SignedAt")
                    .HasColumnType("INTEGER")
                    .HasColumnName("signed_at");

                b.Property<string>("SignerPublicKey")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("signer_public_key");

                b.Property<string>("SigningNonce")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("signing_nonce");

                b.HasKey("CorrelationId");

                b.ToTable("compromised_device_responses", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.AdministratorAuthorityRecord", b =>
            {
                b.Property<long>("Sequence")
                    .HasColumnType("INTEGER")
                    .HasColumnName("sequence");

                b.Property<string>("AdmissionSignature")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("")
                    .HasColumnName("admission_signature");

                b.Property<string>("AdmittedByPartyId")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("")
                    .HasColumnName("admitted_by_party");

                b.Property<string>("AdmittedByPublicKey")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("")
                    .HasColumnName("admitted_by_key");

                b.Property<int>("Event")
                    .HasColumnType("INTEGER")
                    .HasColumnName("event");

                b.Property<long?>("ExpiresAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("expires_at");

                b.Property<string>("Hash")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("hash");

                b.Property<bool>("IsGenesisAdmission")
                    .HasColumnType("INTEGER")
                    .HasColumnName("is_genesis_admission");

                b.Property<string>("MemberPublicKey")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("")
                    .HasColumnName("member_public_key");

                b.Property<long>("OccurredAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("occurred_at");

                b.Property<string>("PartyId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("party_id");

                b.Property<string>("PreviousHash")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("prev_hash");

                b.Property<int>("Provenance")
                    .HasColumnType("INTEGER")
                    .HasColumnName("provenance");

                b.Property<string>("Reason")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("")
                    .HasColumnName("reason");

                b.Property<string>("TeamId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("team_id");

                b.HasKey("Sequence");

                b.HasIndex("TeamId", "PartyId");

                b.ToTable("administrator_authority", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Roster.NodeRosterRecord", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<string>("AdmittedByPartyId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("admitted_by_party");

                b.Property<string>("AdmittedByPublicKey")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("admitted_by_key");

                b.Property<string>("AdmittedViaTokenId")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("")
                    .HasColumnName("admitted_via_token_id");

                b.Property<string>("DmPublicKeyB64Url")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("")
                    .HasColumnName("dm_public_key");

                b.Property<bool>("IsGenesis")
                    .HasColumnType("INTEGER")
                    .HasColumnName("is_genesis");

                b.Property<long>("IssuedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("issued_at");

                b.Property<int>("Kind")
                    .HasColumnType("INTEGER")
                    .HasColumnName("kind");

                b.Property<string>("MintingSessionEvidence")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("")
                    .HasColumnName("minting_session_evidence");

                b.Property<string>("NonceGuid")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("nonce");

                b.Property<string>("PartyId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("party_id");

                b.Property<string>("PermissionsJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("permissions");

                b.Property<string>("PublicKeyB64Url")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("public_key");

                b.Property<string>("SignatureB64Url")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("signature");

                b.Property<string>("TeamId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("team_id");

                b.Property<string>("TransportPublicKeyB64Url")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("")
                    .HasColumnName("transport_public_key");

                b.Property<string>("XWingPublicKeyB64Url")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT")
                    .HasDefaultValue("")
                    .HasColumnName("xwing_public_key");

                b.HasKey("Id");

                b.HasIndex("TeamId");

                b.HasIndex("TeamId", "IssuedAtUtc");

                b.ToTable("roster_records", (string)null);
            });
#pragma warning restore 612, 618
    }
}
