// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Identity;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Identity.WebSessionMigrations;

[DbContext(typeof(NodeLocalWebSessionDbContext))]
partial class NodeLocalWebSessionDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260716214207_WebSessionRecords";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.WebAccountAccessChallengeRecord", b =>
            {
                b.Property<string>("ChallengeId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("challenge_id");

                b.Property<long>("AbsoluteExpiresAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("absolute_expires_at_utc");

                b.Property<string>("AccountId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("account_id");

                b.Property<long>("AccountSecurityVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("account_security_version");

                b.Property<long?>("ConsumedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("consumed_at_utc");

                b.Property<string>("CoordinationCorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("coordination_correlation_id");

                b.Property<string>("HandleDigest")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("handle_digest");

                b.Property<long>("IssuedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("issued_at_utc");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<long?>("RevokedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("revoked_at_utc");

                b.HasKey("ChallengeId");

                b.HasIndex("AbsoluteExpiresAtUtc")
                    .HasDatabaseName("ix_web_account_challenge_expiry");

                b.HasIndex("AccountId")
                    .HasDatabaseName("ix_web_account_challenge_account");

                b.HasIndex("HandleDigest")
                    .IsUnique()
                    .HasDatabaseName("ux_web_account_challenge_handle_digest");

                b.ToTable("web_account_access_challenges", null, t =>
                    {
                        t.HasCheckConstraint("ck_web_account_challenge_expiry", "absolute_expires_at_utc > issued_at_utc");

                        t.HasCheckConstraint("ck_web_account_challenge_owner_version", "owner_version > 0");
                    });
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.WebAntiforgeryStateRecord", b =>
            {
                b.Property<string>("AntiforgeryStateId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("antiforgery_state_id");

                b.Property<long>("AbsoluteExpiresAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("absolute_expires_at_utc");

                b.Property<string>("AccountId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("account_id");

                b.Property<string>("Audience")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("audience");

                b.Property<long?>("ConsumedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("consumed_at_utc");

                b.Property<string>("CoordinationCorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("coordination_correlation_id");

                b.Property<long>("IssuedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("issued_at_utc");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<long?>("RevokedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("revoked_at_utc");

                b.Property<string>("SubjectCorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("subject_correlation_id");

                b.Property<string>("TokenDigest")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("token_digest");

                b.HasKey("AntiforgeryStateId");

                b.HasIndex("AbsoluteExpiresAtUtc")
                    .HasDatabaseName("ix_web_antiforgery_state_expiry");

                b.HasIndex("TokenDigest")
                    .IsUnique()
                    .HasDatabaseName("ux_web_antiforgery_state_token_digest");

                b.HasIndex("Audience", "SubjectCorrelationId")
                    .IsUnique()
                    .HasFilter("consumed_at_utc IS NULL AND revoked_at_utc IS NULL")
                    .HasDatabaseName("ux_web_antiforgery_state_active_subject");

                b.ToTable("web_antiforgery_states", null, t =>
                    {
                        t.HasCheckConstraint("ck_web_antiforgery_state_expiry", "absolute_expires_at_utc > issued_at_utc");

                        t.HasCheckConstraint("ck_web_antiforgery_state_owner_version", "owner_version > 0");
                    });
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.WebInstallationSessionRecord", b =>
            {
                b.Property<string>("SessionCorrelationId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("session_correlation_id");

                b.Property<long>("AbsoluteExpiresAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("absolute_expires_at_utc");

                b.Property<string>("AccountId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("account_id");

                b.Property<long>("AccountSecurityVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("account_security_version");

                b.Property<string>("AntiforgeryStateId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("antiforgery_state_id");

                b.Property<long>("AuthorizationEpoch")
                    .HasColumnType("INTEGER")
                    .HasColumnName("authorization_epoch");

                b.Property<string>("CoordinationCorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("coordination_correlation_id");

                b.Property<string>("HandleDigest")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("handle_digest");

                b.Property<string>("InstallationGrantId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("installation_grant_id");

                b.Property<long>("InstallationGrantOwnerVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("installation_grant_owner_version");

                b.Property<long>("IssuedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("issued_at_utc");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.HasKey("SessionCorrelationId");

                b.HasIndex("AbsoluteExpiresAtUtc")
                    .HasDatabaseName("ix_web_installation_session_expiry");

                b.HasIndex("AccountId")
                    .HasDatabaseName("ix_web_installation_session_account");

                b.HasIndex("AntiforgeryStateId")
                    .HasDatabaseName("ix_web_installation_session_antiforgery");

                b.HasIndex("HandleDigest")
                    .IsUnique()
                    .HasDatabaseName("ux_web_installation_session_handle_digest");

                b.ToTable("web_installation_sessions", null, t =>
                    {
                        t.HasCheckConstraint("ck_web_installation_session_authority_versions", "account_security_version > 0 AND installation_grant_owner_version > 0 AND authorization_epoch > 0");

                        t.HasCheckConstraint("ck_web_installation_session_expiry", "absolute_expires_at_utc > issued_at_utc AND absolute_expires_at_utc <= issued_at_utc + 900000");

                        t.HasCheckConstraint("ck_web_installation_session_handle_digest", "length(handle_digest) = 64 AND handle_digest NOT GLOB '*[^0-9A-F]*'");

                        t.HasCheckConstraint("ck_web_installation_session_owner_version", "owner_version > 0");
                    });
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.WebSessionRevocationRecord", b =>
            {
                b.Property<string>("RevocationId")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("revocation_id");

                b.Property<string>("AccountId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("account_id");

                b.Property<string>("Audience")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("TEXT")
                    .HasColumnName("audience");

                b.Property<string>("CoordinationCorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("coordination_correlation_id");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<string>("ReasonCode")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("reason_code");

                b.Property<long>("RevokedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("revoked_at_utc");

                b.Property<string>("SubjectCorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("subject_correlation_id");

                b.Property<string>("SupersededByCorrelationId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("superseded_by_correlation_id");

                b.HasKey("RevocationId");

                b.HasIndex("AccountId")
                    .HasDatabaseName("ix_web_session_revocation_account");

                b.HasIndex("Audience", "SubjectCorrelationId")
                    .IsUnique()
                    .HasDatabaseName("ux_web_session_revocation_subject");

                b.ToTable("web_session_revocations", null, t =>
                    {
                        t.HasCheckConstraint("ck_web_session_revocation_owner_version", "owner_version > 0");
                    });
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Identity.WebUserSessionRecord", b =>
            {
                b.Property<string>("SessionCorrelationId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("session_correlation_id");

                b.Property<long>("AbsoluteExpiresAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("absolute_expires_at_utc");

                b.Property<string>("AccountId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("account_id");

                b.Property<long>("AccountSecurityVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("account_security_version");

                b.Property<string>("AntiforgeryStateId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("antiforgery_state_id");

                b.Property<long>("AuthorizationEpoch")
                    .HasColumnType("INTEGER")
                    .HasColumnName("authorization_epoch");

                b.Property<string>("CanonicalPartyReference")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("canonical_party_reference");

                b.Property<string>("CoordinationCorrelationId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("coordination_correlation_id");

                b.Property<string>("HandleDigest")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("handle_digest");

                b.Property<long>("IdleExpiresAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("idle_expires_at_utc");

                b.Property<long>("IssuedAtUtc")
                    .HasColumnType("INTEGER")
                    .HasColumnName("issued_at_utc");

                b.Property<string>("MembershipId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("membership_id");

                b.Property<long>("MembershipOwnerVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("membership_owner_version");

                b.Property<long>("OwnerVersion")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER")
                    .HasColumnName("owner_version");

                b.Property<string>("PinnedGrantOwnerVersions")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("pinned_grant_owner_versions_json");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("TenantPrincipalId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_principal_id");

                b.HasKey("SessionCorrelationId");

                b.HasIndex("AbsoluteExpiresAtUtc")
                    .HasDatabaseName("ix_web_user_session_expiry");

                b.HasIndex("AntiforgeryStateId")
                    .HasDatabaseName("ix_web_user_session_antiforgery");

                b.HasIndex("HandleDigest")
                    .IsUnique()
                    .HasDatabaseName("ux_web_user_session_handle_digest");

                b.HasIndex("AccountId", "TenantId")
                    .HasDatabaseName("ix_web_user_session_account_tenant");

                b.HasIndex("TenantId", "MembershipId")
                    .HasDatabaseName("ix_web_user_session_membership");

                b.ToTable("web_user_sessions", null, t =>
                    {
                        t.HasCheckConstraint("ck_web_user_session_absolute_expiry", "absolute_expires_at_utc > issued_at_utc");

                        t.HasCheckConstraint("ck_web_user_session_idle_expiry", "idle_expires_at_utc > issued_at_utc AND idle_expires_at_utc <= absolute_expires_at_utc");

                        t.HasCheckConstraint("ck_web_user_session_owner_version", "owner_version > 0");
                    });
            });
#pragma warning restore 612, 618
    }
}
