// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Scheduling;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Scheduling.Migrations;

[DbContext(typeof(NodeLocalSchedulingDbContext))]
partial class NodeLocalSchedulingDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260712120000_AddSchedulingDefinitionDrafts";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Scheduling.NodeSchedulingDraftAuditRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("AuditId")
                    .HasMaxLength(36)
                    .HasColumnType("TEXT")
                    .HasColumnName("audit_id");

                b.Property<string>("ActorId")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT")
                    .HasColumnName("actor_id");

                b.Property<string>("DefinitionId")
                    .IsRequired()
                    .HasMaxLength(160)
                    .HasColumnType("TEXT")
                    .HasColumnName("definition_id");

                b.Property<DateTimeOffset>("OccurredAtUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("occurred_at_utc");

                b.Property<int>("Revision")
                    .HasColumnType("INTEGER")
                    .HasColumnName("revision");

                b.HasKey("TenantId", "AuditId");

                b.HasIndex("TenantId", "DefinitionId", "Revision")
                    .IsUnique();

                b.ToTable("scheduling_definition_draft_audit", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Scheduling.NodeSchedulingDraftRow", b =>
            {
                b.Property<string>("TenantId")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant_id");

                b.Property<string>("DefinitionId")
                    .HasMaxLength(160)
                    .HasColumnType("TEXT")
                    .HasColumnName("definition_id");

                b.Property<int>("Revision")
                    .HasColumnType("INTEGER")
                    .HasColumnName("revision");

                b.Property<string>("DefinitionJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("definition_json");

                b.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("updated_at_utc");

                b.Property<string>("UpdatedBy")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT")
                    .HasColumnName("updated_by");

                b.HasKey("TenantId", "DefinitionId", "Revision");

                b.HasIndex("TenantId", "DefinitionId", "Revision");

                b.ToTable("scheduling_definition_drafts", (string)null);
            });
#pragma warning restore 612, 618
    }
}
