// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Packs;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Packs.Migrations;

[DbContext(typeof(NodeLocalPacksDbContext))]
[Migration("20260707044248_PacksInitial")]
partial class _20260707044248_PacksInitial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Packs.PackInstalledVersionRow", b =>
            {
                b.Property<string>("Tenant")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant");

                b.Property<string>("PackKey")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("pack_key");

                b.Property<string>("Version")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("version");

                b.Property<int>("Lifecycle")
                    .HasColumnType("INTEGER")
                    .HasColumnName("lifecycle");

                b.Property<string>("PayloadJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("payload_json");

                b.HasKey("Tenant", "PackKey", "Version");

                b.HasIndex("Tenant", "PackKey", "Lifecycle");

                b.ToTable("pack_installed_versions", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Packs.PackKeyOwnershipRow", b =>
            {
                b.Property<string>("Tenant")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant");

                b.Property<string>("ContentKey")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT")
                    .HasColumnName("content_key");

                b.Property<string>("OwningPackKey")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("owning_pack_key");

                b.HasKey("Tenant", "ContentKey");

                b.ToTable("pack_key_ownership", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Packs.PackTenantOverrideRow", b =>
            {
                b.Property<string>("Tenant")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant");

                b.Property<string>("PackKey")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("pack_key");

                b.Property<string>("ContentKey")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT")
                    .HasColumnName("content_key");

                b.Property<string>("OverlayJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("overlay_json");

                b.HasKey("Tenant", "PackKey", "ContentKey");

                b.ToTable("pack_overrides", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Packs.PackWatermarkRow", b =>
            {
                b.Property<string>("Tenant")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant");

                b.Property<string>("PackKey")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("pack_key");

                b.Property<string>("FloorsJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("floors_json");

                b.Property<string>("Version")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("version");

                b.HasKey("Tenant", "PackKey");

                b.ToTable("pack_watermarks", (string)null);
            });
#pragma warning restore 612, 618
    }
}
