// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Packs;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Packs.Migrations;

[DbContext(typeof(NodeLocalPacksDbContext))]
partial class NodeLocalPacksDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260902120000_AddPackProjectionAdmissions";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Packs.FeedChannelSequenceRow", b =>
            {
                b.Property<string>("Tenant")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant");

                b.Property<string>("ChannelId")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("channel_id");

                b.Property<long>("HighWaterSequence")
                    .HasColumnType("INTEGER")
                    .HasColumnName("high_water_sequence");

                b.HasKey("Tenant", "ChannelId");

                b.ToTable("feed_channel_sequences", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Packs.PackInstalledVersionRow", b =>
            {
                b.Property<string>("Tenant")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant");

                b.Property<string>("PackKey")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("pack_key");

                b.Property<string>("Version")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("version");

                b.Property<int>("Lifecycle")
                    .HasColumnType("INTEGER")
                    .HasColumnName("lifecycle");

                b.Property<string>("PayloadJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("payload_json");

                b.HasKey("Tenant", "PackKey", "Version");

                b.HasIndex("Tenant", "PackKey", "Lifecycle");

                b.ToTable("pack_installed_versions", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Packs.PackKeyOwnershipRow", b =>
            {
                b.Property<string>("Tenant")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant");

                b.Property<string>("ContentKey")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT")
                    .HasColumnName("content_key");

                b.Property<string>("OwningPackKey")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("owning_pack_key");

                b.HasKey("Tenant", "ContentKey");

                b.ToTable("pack_key_ownership", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Packs.PackProjectionAdmissionRow", b =>
            {
                b.Property<Guid>("AdmissionId").HasColumnType("TEXT").HasColumnName("admission_id");
                b.Property<string>("Tenant").IsRequired().HasMaxLength(256).HasColumnType("TEXT").HasColumnName("tenant");
                b.Property<string>("PackId").IsRequired().HasMaxLength(256).HasColumnType("TEXT").HasColumnName("pack_id");
                b.Property<string>("PackVersion").IsRequired().HasMaxLength(64).HasColumnType("TEXT").HasColumnName("pack_version");
                b.Property<string>("Principal").IsRequired().HasMaxLength(512).HasColumnType("TEXT").HasColumnName("principal");
                b.Property<DateTimeOffset>("Instant").HasColumnType("TEXT").HasColumnName("instant");
                b.Property<string>("DerivationIdsJson").IsRequired().HasColumnType("TEXT").HasColumnName("derivation_ids_json");
                b.Property<bool>("Projected").HasColumnType("INTEGER").HasColumnName("projected");
                b.HasKey("AdmissionId");
                b.HasIndex("Tenant", "Projected");
                b.ToTable("pack_projection_admissions", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Packs.PackTenantOverrideRow", b =>
            {
                b.Property<string>("Tenant")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant");

                b.Property<string>("PackKey")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("pack_key");

                b.Property<string>("ContentKey")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT")
                    .HasColumnName("content_key");

                b.Property<string>("OverlayJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("overlay_json");

                b.HasKey("Tenant", "PackKey", "ContentKey");

                b.ToTable("pack_overrides", (string)null);
            });

        modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Packs.PackWatermarkRow", b =>
            {
                b.Property<string>("Tenant")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("tenant");

                b.Property<string>("PackKey")
                    .HasMaxLength(256)
                    .HasColumnType("TEXT")
                    .HasColumnName("pack_key");

                b.Property<string>("FloorsJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("floors_json");

                b.Property<string>("Version")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("version");

                b.HasKey("Tenant", "PackKey");

                b.ToTable("pack_watermarks", (string)null);
            });
#pragma warning restore 612, 618
    }
}
