// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Harborline.Api.LocalNodeHost.Data.Payroll;

#nullable disable

namespace Harborline.Api.LocalNodeHost.Data.Payroll.Migrations
{
    [DbContext(typeof(NodeLocalPayrollDbContext))]
    partial class NodeLocalPayrollDbContextModelSnapshot : ModelSnapshot
    {
        // If you encounter a merge conflict in the line below, it means you need to
        // discard one of the migration branches and recreate its migrations on top of
        // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
        public override string LastMigrationId => "20260616231430_PayrollInitial";

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115");

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Payroll.EmployeeRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CostCentreId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cost_centre_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("PartyId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("party_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WageExpenseAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("wage_expense_account_id");

                    b.Property<string>("WagesPayableAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("wages_payable_account_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsActive");

                    b.ToTable("payroll_employees", (string)null);
                });

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Payroll.FilingObligationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_complete");

                    b.Property<string>("JurisdictionCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("jurisdiction_code");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("PeriodEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("period_end");

                    b.Property<string>("PeriodStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("period_start");

                    b.Property<string>("SourcePayRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_pay_run_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "DueDate");

                    b.ToTable("payroll_filing_obligations", (string)null);
                });

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Payroll.PayRunLineRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DeductionPayableAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("deduction_payable_account_id");

                    b.Property<decimal>("EmployeeDeductions")
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_deductions");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("EmployerLiabilityAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("employer_liability_amount");

                    b.Property<string>("EmployerLiabilityExpenseAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("employer_liability_expense_account_id");

                    b.Property<string>("EmployerLiabilityPayableAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("employer_liability_payable_account_id");

                    b.Property<decimal>("GrossWage")
                        .HasColumnType("TEXT")
                        .HasColumnName("gross_wage");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("PayRunId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pay_run_id");

                    b.Property<decimal>("TaxWithheld")
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_withheld");

                    b.Property<string>("TaxWithheldAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_withheld_account_id");

                    b.HasKey("Id");

                    b.HasIndex("PayRunId");

                    b.ToTable("payroll_pay_run_lines", (string)null);
                });

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Payroll.PayRunRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefaultDeductionPayableAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_deduction_payable_account_id");

                    b.Property<string>("DefaultEmployerLiabilityExpenseAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_employer_liability_expense_account_id");

                    b.Property<string>("DefaultEmployerLiabilityPayableAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_employer_liability_payable_account_id");

                    b.Property<string>("DefaultTaxWithheldAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_tax_withheld_account_id");

                    b.Property<string>("JournalEntryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("journal_entry_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("PeriodEnd")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("period_end");

                    b.Property<string>("PeriodStart")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("period_start");

                    b.Property<string>("PostingDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("posting_date");

                    b.Property<string>("ReversalEntryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reversal_entry_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PostingDate");

                    b.ToTable("payroll_pay_runs", (string)null);
                });

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Payroll.PayRunLineRecord", b =>
                {
                    b.HasOne("Harborline.Api.LocalNodeHost.Data.Payroll.PayRunRecord", null)
                        .WithMany("Lines")
                        .HasForeignKey("PayRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Harborline.Api.LocalNodeHost.Data.Payroll.PayRunRecord", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
